unipartdigital/udes-open

addons/udes_core/models/stock_move.py

[FIX] udes_core: override stock.move._unreserve_initial_demand()

---

addons/udes_stock/models/product_template.py
addons/udes_stock/views/product_template.xml

[IMP] udes_stock: add hazardous field to product template

---

addons/udes_security/__init__.py
addons/udes_security/__manifest__.py
addons/udes_security/controllers/__init__.py
addons/udes_security/controllers/redirect.py

Block absolute redirections via the /web and /web/login HTTP routes.

[ADD] udes_security: Add udes_security module and open redirect filter

---

addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_create_picking.py

[TEST] udes_stock: add initial unit test for create picking

---

addons/udes_stock/controllers/print_printer.py

[FIX] udes_stock: Fix typo in /api/print-printer/spool-report controller

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_splitting.py

Story 1515: Split pickings by pallet

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/views/stock_picking_type.xml

[ADD] udes_stock: Add batch_id to get_pickings

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_picking.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking_type.py

The request schema will now require only the `move_line_ids` array entry (mandatory).

[IMP] (1855) Update picking::suggested_locations endpoint

---

addons/udes_sale_stock/models/__init__.py
addons/udes_sale_stock/models/stock_move_line.py
addons/udes_stock/models/stock_move_line.py

[REF] udes_stock, udes_sale_stock: Move product_packaging to sale_stock

---

addons/udes_stock/__manifest__.py
addons/udes_stock/data/stock_config.xml

Signed-off-by: Luke Barone-Adesi <luke.barone-adesi@unipart.io>

[IMP] enable order-specific routes by default

---

addons/udes_stock/tests/common.py

[TEST] udes_stock: Add procurement rules to outbound route

---

addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/tests/test_picking_batch.py

- Make the criteria an optional arg for the get_next_task
method of the Batch model, so to enable testing via
dependency injection.
- Add a trivial test that relies on the package name
for the ordering of move lines.

[ADD] Trivial test for batch::next ordering criteria

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_location.py
addons/udes_stock/controllers/stock_picking_batch.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py

[WIP] endpoint change putaway exception handling

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

[IMP] udes_stock: Under receive picking type flag

---

addons/udes_delivery_slot/LICENSE
addons/udes_delivery_slot/__init__.py
addons/udes_delivery_slot/__manifest__.py
addons/udes_delivery_slot/data/delivery_slot_data.xml
addons/udes_delivery_slot/models/__init__.py
addons/udes_delivery_slot/models/delivery_slot.py
addons/udes_delivery_slot/models/sale_order.py
addons/udes_delivery_slot/security/ir.model.access.csv
addons/udes_delivery_slot/tests/__init__.py
addons/udes_delivery_slot/tests/test_delivery_slot.py
addons/udes_delivery_slot/views/delivery_slot_views.xml
addons/udes_delivery_slot/views/sale_order_views.xml

[NEW] udes_delivery_slot: Module to model delivery slots

---

addons/udes_stock/models/stock_move_line.py

Fixes bug in suggested locations

[FIX] udes_stock: Make any_destination_locations_default use zone 

---

addons/udes_stock/models/stock_picking.py

Throw a validation error when auto-batching to user in case of the user already having an in progress batch.

[IMP] udes_stock: Prevent multiple active batches being created automatically

---

addons/udes_stock/controllers/stock_location.py

[FIX] udes_stock: Allow non admin users to block a location via endpoint

---

addons/udes_stock/models/stock_picking.py

Changed valid_locations to find only the child locations that are
also current destination locations
User-story: 1887

[ADD] udes_stock: Changed valid_locations to find valid destinations

---

addons/udes_stock/data/locations.xml
addons/udes_stock/data/picking_types.xml

[IMP] udes_stock: Fix quarantine location and remove unused fields

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: Draft pickings displayed in Kanban view

---

addons/udes_stock/report/report_stockpicking_operations.xml

[IMP] udes_stock: Use order origin for the barcode in PDF report

---

addons/udes_product_expiry/LICENSE
addons/udes_product_expiry/__init__.py
addons/udes_product_expiry/__manifest__.py
addons/udes_product_expiry/models/__init__.py
addons/udes_product_expiry/models/stock_move_line.py
addons/udes_product_expiry/models/stock_picking.py
addons/udes_product_expiry/report/report_deliveryslip.xml
addons/udes_product_expiry/views/stock_move_line_views.xml
addons/udes_product_expiry/views/stock_picking_views.xml
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/report/deliveryslip_templates.xml
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_generate_lot.py
addons/udes_stock/views/stock_picking_type.xml

Used to determine if expiry dates should be requested to the user
for a given picking type.

[IMP] udes_stock: Add confirm expiry date flag to picking type

---

addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: Partner field filtered to only see vendors

---

addons/udes_stock/README.md
addons/udes_stock/controllers/main.py
addons/udes_stock/controllers/stock_picking.py
addons/udes_stock/controllers/stock_picking_batch.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_picking_batch.py
addons/udes_stock/views/stock_picking_batch.xml
addons/udes_stock/views/stock_picking_type.xml

Add more granular states to batch using pick state and user.
Add new endpoints for assigning and unassigning batches.
Add new picking type options for goodsout workflow.
User-story: 2163

[ADD] udes_stock: batch: new states, assign, unassign

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py

Created new function to prepare all the extra fields needed for the
new pickings when at _new_picking_for_group().
The new function now returns date_done and partner_id in addition
to origin.
User-story: 2176

[IMP] udes_stock: Keep more fields when refactoring moves/move lines

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_picking_batch.py
addons/udes_stock/views/stock_picking_type.xml

When this flag is set to false, a message asking to contact team leader
will be raised instead of performing the usual unpickable item behaviour.
User-story: 2551

[IMP] udes_stock: Add handle unpickable items flag to picking type

---

addons/udes_sale_stock/models/sale_order.py

[IMP] udes_sale_stock: Index added to origin field

---

addons/udes_sale_stock/models/partner_pii.py

[IMP] udes_sale_stock: Log PII views

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

Add confirm batch name to stock.picking.type

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

[IMP] udes_stock: Add enable confirmations at picking type

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/sale_order_line.py
addons/udes_sale_stock/views/sale_order_views.xml

[IMP] udes_sale_sock: Add is_cancelled field to sale.order.line

---

addons/udes_stock/controllers/stock_move_line.py

[IMP] Update suggested_locations endpoint to accept POST requests

---

addons/udes_stock/views/stock_picking.xml

[IMP] Change bootstrap columns to allow for longer numbers

---

addons/udes_stock/models/stock_picking_batch.py

Drop off picked was using update_picking() to validate each individual
picking that is being dropped off. Instead use action_done() over all
the pickings together to use the advantage of validating pickings and
moves in batches, which also calls refactoring one time instead of N.
User-story: 3084

[IMP] udes_stock: Validate pickings in batches at drop_off_picked

---

addons/udes_sale_stock/__manifest__.py

Signed-off-by: Luke Barone-Adesi <luke.barone-adesi@unipart.io>

[FIX] udes-open: add edi_sale to manifest

---

addons/udes_stock/views/stock_location.xml

Signed-off-by: Richard Whitefoot <richard.whitefoot@unipart.io>

[IMP] udes_stock: Location Policy field readonly

---

addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/views/stock_warehouse.xml

[IMP] udes_stock: Add RPC timing boolean flag to warehouse config

---

addons/udes_stock/models/stock_picking_batch.py

Logic was broken, trying to update picking_id of deleted picking
Instead: do not update when refactor is used, update new picking
to be in current batch of work.

[FIX] udes_stock: Refactoring and unpickable item logic

---

addons/udes_sale_stock/models/sale_order_line.py

Defining and assigning the timestamp of cancellation
to sale order lines.
User-story: 3020

[ADD] udes_sale_stock: `cancel_date` field to SaleOrderLine

---

addons/udes_stock/models/stock_move_line.py

[IMP] udes_stock: Only compute refatoring key when needed for move lines

---

addons/udes_stock/models/stock_picking_batch.py

[IMP] udes_stock: Add u_ephemeral flag to returned batch data

---

addons/udes_sale_stock/models/sale_order.py

Ordering of sale order is now as follows:
requested_date asc, priority desc, id asc

[IMP] udes_sale_stock: Define _order for sale_order

---

addons/udes_stock/models/product_template.py
addons/udes_stock/views/product_template.xml

[IMP] udes_stock: Add u_pallet_qty to product template

---

addons/udes_purchase/__manifest__.py
addons/udes_purchase/data/routes.xml
addons/udes_purchase/models/procurement.py
addons/udes_stock/__manifest__.py
addons/udes_stock/data/picking_types.xml
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/wizard/__init__.py
addons/udes_stock/wizard/replen_views.py
addons/udes_stock/wizard/replen_views.xml

[IMP] udes_stock:  Add replen picking type

---

addons/udes_stock/views/stock_warehouse.xml

This allows the users to change it to use a different route.
User-story: 3488

[IMP] udes_stock: Show default delivery route at warehouse config

---

addons/udes_stock/models/stock_picking_batch.py

[FIX] udes_stock: Handle multiple batches at mark_as_todo()

---

addons/udes_stock/models/stock_move_line.py

Signed-off-by: andrewm <andrew.martin@unipart.io>

[FIX] fix crash on adding product to pick with parent destination loc

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_splitting.py

If all the remaining moves of a picking are to be placed in a new picking,
the existing picking is reused instead of creating a new one.
User-story: 3591
Task: 3738

[IMP] udes_stock: Re-use existing picks in refactor when appropriate

---

addons/udes_stock/models/stock_picking.py

[IMP] udes_stock: Use savepoint to rollback at reserve_stock

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

Boolean flag to enable pallets to be released one at a time.

[ADD] udes_stock: Add boolean flag for enabling part pallets

---

addons/udes_stock/__manifest__.py
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/wizard/refactor_views.xml
addons/udes_stock/wizard/reservation_views.xml
addons/udes_stock/wizard/stock_picking_to_batch_views.xml

Disable archive and unarchive buttons
Disable Delete button for non-Trusted Users

Story/4144 Only allow users to export pickings from the action menu

---

addons/udes_sale_stock/__manifest__.py

Added a default chart of accounts to ensure that a customer/ vendor can be added via the UI.
Task/4332

[FIX] udes_sale_stock: Added dependency on l10n_uk

---

addons/udes_stock/models/stock_picking.py

[IMP] udes_stock: Mimic Odoo's retry behaviour at reserve_stock()

---

addons/udes_security/controllers/redirect.py

[FIX] udes_security: Further measures to tackle open redirects

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_location.py
addons/udes_stock/models/stock_location.py

Here we specify and implement a new API endpoint
for checking whether a package exists and is
located in a given location.
Epic: 3735
User-story: 4564

[IMP] (4564) New location::is_compatible_package endpoint

---

addons/udes_stock/models/stock_move.py

[IMP] udes_stock: Unlink empty pickings at push from drop

---

addons/udes_stock/models/product_category.py
addons/udes_stock/models/stock_picking_type.py

[ADD] hds: Add sequence for product category

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py

can be displayed to users when picking with handhelds.

[IMP] udes_stock: Add picking guidance info to picking info that

---

addons/udes_security/models/res_groups.py
addons/udes_security/models/res_users.py

The function that checks if the user trying to add/remove trusted user
security group is admin can be abstracted to receive the group as a
paramter, so that it can be used for other security groups.
User-story: 4607

[IMP] udes_security: Abstract only admin security check

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/test_get_current_demand.py

get_current_demand will return the current demand on all (or specified)
product_ids caused by sale orders;

[IMP] udes_sale_stock: Adding get_current_demand to SO model

---

addons/udes_stock/views/stock_picking.xml

Change naming and add a confirmation box.
Task: 9059

[IMP] udes_stock: Replace cancel button with a clearer instruction

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking_type.py

[ADD] Add type field to task

---

addons/udes_stock/models/stock_move_line.py

[IMP] udes_stock: Block changes to important move line fields once done

---

addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/tests/test_picking_batch.py

[IMP] udes_stock: unit tests for continuation batches

---

Dockerfile
addons/edi_notifier/data/mail_templates.xml
addons/edi_notifier/models/email_notifier.py
addons/edi_notifier/models/notifier.py
addons/edi_notifier/tests/test_edi_notifier.py
addons/edi_notifier/views/notifiers.xml

[ADD] edi_notifier: Add notes and issues to email

---

addons/udes_security/__manifest__.py
addons/udes_security/models/res_users.py
addons/udes_security/tests/__init__.py
addons/udes_security/tests/test_single_session.py
addons/udes_security/views/res_users_views.xml

u_restrict_to_single_session flag added which restricts a user to a
single session. Upon login all active sessions for a user are deleted.
(story/9772)

[IMP] udes_security: Add flag to restrict a user to a single session

---

addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Add indexes for stock.move.line

---

addons/udes_common/__init__.py
addons/udes_common/__manifest__.py
addons/udes_common/models/__init__.py
addons/udes_common/models/models.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/test_iterators.py
addons/udes_common/tools/__init__.py
addons/udes_common/tools/iterators.py
addons/udes_common/tools/statistics.py
addons/udes_common/tools/tracing.py

Adds useful methods to existing models:
- sliced
- groupby
- batched
- getter
- statistics
- trace
Add iterator helpers:
- sliced
- ranged
- batched

[ADD] udes_common: Add common components for UDES

---

addons/udes_stock/data/picking_types.xml

[9138] [FIX]: Fix the ordering of operation types in the UI

---

addons/udes_sale_stock/models/sale_order.py

[REF] udes_sale_stock: Create index for sale order ordering

---

addons/get_info/__init__.py
addons/get_info/__manifest__.py
addons/get_info/models/__init__.py
addons/get_info/models/models.py
addons/get_info/models/stock_location.py
addons/get_info/tests/__init__.py
addons/get_info/tests/test_get_info.py

Have a seperate module that determines how information can be recursively obtianed.
User-story: 9944

[ADD] udes_13: Add get_info submodule

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_move.py

By default it is now bypassed, but in some cases still it shouldn't.

 User-story: 10561 - Do not bypass_reservation_update at _unreserve_inital_demand

---

addons/udes_stock/views/stock_inventory.xml

[ADD] udes_stock: Add reserved stock column stock move lines

---

addons/udes_sale_stock/views/sale_order_views.xml

[ADD] udes_sale_stock: Show product_packaging on order line in orders

---

addons/udes_stock/models/stock_warehouse.py

[FIX] udes_stock: Disallow adjusting reserved stock by default

---

addons/udes_sale_stock/models/sale_order.py

Split is done for readability and so that the searching for unavailability may be re-used. 
User-story: 10610

[IMP] udes_sale_stock: Split cancel_orders_without_availability

---

addons/udes_sale_stock/models/sale_order.py

Add ability to specify states to confirm to allow custom
states defined outside the module to be used.
User-story: 10609

[IMP] udes_sale_stock: Add optional states argument to confirm orders

---

addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/test_cancel_unfulfillable.py
addons/udes_sale_stock/tests/test_get_current_demand.py
addons/udes_sale_stock/tests/test_sale_order_state.py
addons/udes_stock/tests/common.py

[ADD] udes_sale_stock: Add unit tests for sale order state computation

---

addons/udes_sale_stock/models/sale_order.py

Add check in confirm_orders to see if self contains order records. If it does, system will attempt to confirm these orders. If empty, relevant orders are obtained using _get_confirmation_domain as before.
Story/10607

[IMP] udes_sale_stock: Allow confirm_orders to operate on recordsets

---

addons/udes_sale_stock/models/edi_sale_request_document.py

[IMP] udes_sale_stock: Inject client_order_ref into EDI error reports.

---

addons/udes_sale_stock/models/sale_order.py

[IMP] udes_sale_stock: Allow client_order_ref to be specified for copy

---

addons/udes_stock/models/stock_picking.py

The step that calls _action_assign() on the moves is now in
its own function, so it can be extended/overriden.

User-story: 10454 Abstract reservation at reserve_stock()

---

addons/udes_delivery_control/README.md
addons/udes_delivery_control/__init__.py
addons/udes_delivery_control/__manifest__.py

[ADD] udes_delivery_control: Module creation

---

addons/udes_delivery_control/__manifest__.py
addons/udes_delivery_control/data/picking_types.xml

[ADD] udes_delivery_control: Delivery Control picking type added

---

.travis.yml
Dockerfile
README.md
addons/get_info/models/models.py
addons/suggest_locations/models/suggest_locations_policy.py
addons/suggest_locations/tests/common.py
addons/udes_stock_move/tests/test_change_package_location.py
addons/udes_stock_refactoring/models/refactor.py
addons/udes_stock_refactoring/tests/test_refactoring.py

Changes:
* created Dockerfile, README.md and .travis.yml files to run on travis
* fixed imports in modules
Task: 11499
https://taiga.unipart.digital/project/udescore/task/11499?kanban-status=177
The tests are failing on travis but this is out of scope of the story, I have created an issue for this:
https://taiga.unipart.digital/project/udescore/issue/11537

[ADD] Run tests on travis on 13.0 branch

---

Dockerfile

Task: 11553
https://taiga.unipart.digital/project/udescore/task/11553

[FIX] udes-closed: update Dockerfile to use 13.0 branch of odoo-edi

---

Dockerfile
addons/udes_scanned_by_tracking/__init__.py
addons/udes_scanned_by_tracking/__manifest__.py
addons/udes_scanned_by_tracking/models/__init__.py
addons/udes_scanned_by_tracking/models/stock_move_line.py
addons/udes_scanned_by_tracking/tests/__init__.py
addons/udes_scanned_by_tracking/tests/common.py
addons/udes_scanned_by_tracking/tests/test_scanned_by.py
addons/udes_scanned_by_tracking/views/stock_move_line.xml
addons/udes_scanned_by_tracking/views/stock_picking.xml

[ADD] udes_scanned_by_tracking: Initial commit

---

addons/udes_warehouse_classification/__init__.py
addons/udes_warehouse_classification/controllers/__init__.py
addons/udes_warehouse_classification/controllers/product_template.py

When a product is previously unexpected on a picking we need to be able to
check for messages directly for the product as we can't know beforehand.
User-story: 11593

[ADD] udes_warehouse_classification: Add endpoint for unexpected product

---

addons/udes_delivery_control/__init__.py
addons/udes_delivery_control/controllers/__init__.py
addons/udes_delivery_control/controllers/main.py

Two new endpoints get and confirm picking is added with this commit
Those endpoints will be consumed by mobile client
User-story: 11448
Signed-off-by: Kinner Vachhani

story/11448 - udes_delivery_control

---

addons/udes_stock/models/stock_picking.py

Extend stock.picking._backorder_movelines()
Added optional parameter `picking` so that move lines can be moved
into an existing picking instead of creating a new one.

 User-story: 11547

---

addons/udes_stock/models/stock_quant.py

[ADD] udes_stock: Add parent package to prepare_info 

---

addons/udes_stock/controllers/__init__.py
addons/udes_stock/controllers/product_packaging.py
addons/udes_stock/data/product_packaging.xml
addons/udes_stock/models/__init__.py
addons/udes_stock/models/product_packaging.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml
addons/udes_stock/views/stock_quant_views.xml

Package Type now displayed on Packages.
Pallet and Stillage Package Types added.
API endpoint added to retrieve Package Types.
Parent package type can now be set via `update_picking`.

Story/11788 - Add Package Type support

---

addons/udes_delivery_control/models/picking_extra_fields.py
addons/udes_delivery_control/models/stock_picking.py

[REF] udes_delivery_control: Change trailer_number to be an integer

---

addons/udes_stock/models/stock_quant.py
addons/udes_stock/tests/test_stock_quant.py

[ADD] udes_stock: Add get_movelines_from_quant function

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/tests/test_splitting.py

Add recompute to split_out_move_lines()

User-story: 12091

---

addons/udes_priorities/__init__.py
addons/udes_priorities/models/stock_move.py
addons/udes_priorities/models/stock_picking.py
addons/udes_priorities/models/stock_picking_batch.py
addons/udes_priorities/tests/common.py
addons/udes_priorities/tests/test_stock_picking.py
addons/udes_priorities/views/priorities.xml
addons/udes_priorities/views/priority_groups.xml

[FIX] udes_priority: Fixes for priority propagation

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/views/stock_warehouse.xml

[ADD] udes-stock: Added u_product_barcode_regex field

---

addons/udes_delivery_control/models/picking_extra_fields.py

[FIX] udes_delivery_control

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml
addons/udes_stock/views/stock_warehouse.xml

Added udes_wide_list HTML class to the following config lists:
UDES Config
Pick Refactoring
Pick Warnings
Stock Config

[IMP] udes_stock: Increased column width of config fields

---

addons/udes_stock/models/stock_picking.py

unwipped Signed-off-by: Rho <Rho@Rho.com>

WIP: _12070

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_stock_location_picking_zone.py
addons/udes_stock/views/stock_location.xml

[IMP] udes_stock: Add is_picking_zone to the stock location model.

---

addons/udes_stock/models/stock_picking_batch.py

[IMP] udes_stock: Bypass reassignment of pickings at unpickable_items

---

addons/udes_stock/models/stock_picking.py

[FIX] Fix full package reservation not preserving picking priority

---

addons/udes_stock/views/stock_picking.xml

[FIX] Add missing spacing between Transfers and Package Count buttons

---

addons/udes_stock/controllers/stock_move_line.py
addons/udes_stock/models/stock_picking.py

[FIX] udes_stock: Sort location results in alphanumeric order

---

addons/udes_stock/models/stock_location.py

[ADD] udes_stock: Add ability to change parent package for stock check

---

addons/udes_stock/models/res_users.py

[FIX] udes_stock: Set user default to Handle in Odoo

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_quant.py

Raise error creating moves with qty 0

User-story: 12538

---

addons/udes_stock/models/stock_location.py

Create parent package for count moves

User-story: 12586

---

addons/udes_priorities/models/priority_groups.py

[FIX] udes_priorities: Store picking_type_ids on priority groupds

---

addons/udes_stock/models/stock_picking.py

[ADD] udes_stock: Added ability to set a stock investigation message

---

addons/udes_stock/models/stock_picking_batch.py

User-story: 11963
--------------------------------------------------------------
Remember to change the destination branch once 11962 has been merged!

[IMP] udes_stock: Add has_done_pickings field to batch info

---

addons/udes_stock/models/stock_picking.py

The case of multiple lots on a given package was not handled as
was not needed previously. Extended functionality to address this.
Further added functionality for switching fields on quants for a
picking to allow other values to be switched.
User-story: 12705

[FIX] udes_stock: Allow swapping of lots between packages

---

addons/udes_stock/models/stock_move.py

Added _get_push_move_vals which is now called in refactored _create_moves_for_push. This makes it easier to override the values which should be generated for new moves created for a push rule.
Story/12735

[IMP] udes_stock: Refactored _create_moves_for_push

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/views/stock_picking.xml

Extend stock.picking extra info

User-story: 12679

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py

[IMP] udes_stock: do not perform action assign when creating a batch.

---

addons/udes_warehouse_classification/models/product_product.py

[ADD] udes_warehouse_classification: Add product classification string

---

addons/udes_stock/models/stock_picking.py

Set expected date when creating new move for a picking

User-story: 12964

---

addons/udes_stock/models/stock_move_line.py

Sort move lines by product and id at move_lines_for_qty

User-story: 12851

---

addons/udes_stock/models/stock_picking.py

Return all pickings at _reserve_stock_assign

User-story: 13122

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/tests/test_stock_inventory.py
addons/udes_stock/views/stock_inventory.xml

- Check to see if theoretical quantity has changed since inventory was
started. This prevents incorrect adjustments being made after something
has been moved into/out of a location before adjustment
User-story: 10433

[ADD] udes_stock: Inventory check for changed theoretical quantity

---

addons/udes_sale_stock/tests/test_manual_sale_order_line_cancellation.py

Due to refactoring and/or backorder creation, u_next_picking_ids of the
first picking during test setup is not the same as u_next_picking_ids
once a single item has been picked. Avoid caching u_next_picking_ids early
and only grab it once the first picking has reached the done state.
User-story: 13237

[FIX] udes_sale_stock: Fix sale order line cancellation test case

---

addons/udes_stock/models/stock_picking_batch.py

[IMP] udes_stock: Check batch configuration has same pick types

---

addons/udes_stock/models/product_product.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_product.py

[IMP] udes_stock: Fix bugs in product sync_active_to_templates and add tests

---

addons/udes_stock/models/stock_inventory.py

[ADD] udes_stock: Add always editable fields for Inventory Adjustments

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_refactoring_splitting.py
addons/udes_stock/views/stock_picking_type.xml

[ADD] udes_stock: Can refactor pickings by maximum quantity post assign

---

addons/udes_stock/models/stock_picking_type.py

[IMP] udes_stock: Abstract out target storage options

---

addons/udes_stock/models/stock_location.py
addons/udes_stock/views/stock_location.xml

[ADD] udes_stock: Add option to view children of a location

---

addons/udes_stock/models/stock_move.py

[ADD] udes_open: move_line state to returned info

---

addons/udes_stock/__manifest__.py
addons/udes_stock/wizard/__init__.py
addons/udes_stock/wizard/stock_picking_mark_todo.py
addons/udes_stock/wizard/stock_picking_mark_todo_view.xml

Set multiple picking to Mark As Todo

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking_batch.py

Changes on task type when field u_user_scans is not set on picking type
Adding a new type general in this case
Story: 10456

[ADD] udes_open: Changes on task type

---

addons/udes_stock/models/stock_quant_package.py

Line 146 fixes an issue where a 'False' identifier was previously beind returned
Line 201 fixes formatting on the reserved stock validation message

[FIX] udes_stock - fixed validation messages

---

addons/udes_stock/data/locations.xml
addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_location_countable.py
addons/udes_stock/views/stock_location.xml

Story/15090 Add countable location flag

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/models/stock_location.py

[ADD] udes_stock: Adding Mobile Type field in stock inventory model

---

addons/udes_stock/models/stock_location.py

On databases with a large amount with locations with a high number quants the "location.quant_ids" can slow down the initial computation significantly. As we only care about whether a location has any quants, doing a search count will speed this check up significantly.
Story/15029

[IMP] udes_stock: Compute _compute_state improved for checking quants

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Add method to compute if all mls are done

---

addons/udes_stock/tools/find_multi_location_packages_and_pallets.sql

[ADD] udes_stock: Add tool to check for multi-location packages/pallets

---

addons/udes_stock/tools/find_multi_location_packages_and_pallets.sql

Added package and pallet names to the queries.
Story/x12

[IMP] udes-open: Update to multi-location package script

---

addons/udes_delivery_control/models/stock_picking.py
addons/udes_stock/__init__.py
addons/udes_stock/models/product_product.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/utils.py
addons/udes_warehouse_classification/models/stock_picking.py

on specific modules
Making Workflows module more generic
Story: 4

[ADD] udes_stock: Removing logic dependencies with couple of modules

---

.github/workflows/main.yml
.gitignore
Dockerfile

[IMP] udes-open: Setup CI for unit tests

---

addons/udes_stock/__manifest__.py
addons/udes_stock/views/procurement_views.xml

[ADD] Select view locations through Stock Location Route Rules UI

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: Allow searching by package name

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py

Add u_original_picking_id to track thee first picking.
Add unit tests for u_user_process_partial
User-story: 291

[ADD] udes_open: Add u_original_picking_id o stock.picking

---

addons/udes_common/README.md
addons/udes_common/models/models.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/test_selection_display_name.py

Does what it says on the tin, gets the displayname for a given
selection fields value on a recordset
Also added a readme and filled in what i could for what already exists
User-story: 411

[ADD] udes_common: Helper function selection_value_displayname()

---

addons/udes_security/__manifest__.py
addons/udes_security/models/__init__.py
addons/udes_security/models/models.py
addons/udes_security/models/res_archiving_restriction.py
addons/udes_security/security/ir.model.access.csv
addons/udes_security/static/src/js/basic_view.js
addons/udes_security/tests/__init__.py
addons/udes_security/tests/test_res_archiving_restriction.py
addons/udes_security/views/res_archiving_restriction_views.xml
addons/udes_stock/__manifest__.py
addons/udes_stock/data/res_archiving_restriction.xml

To get an idea what the views look like:
Superuser/user who can access:
Restricted user:
Check is both on frontend and backend to block against malicious users de-activating warehouses via odoorpc

Story/540 archiving restrictions model & config

---

addons/udes_stock/models/stock_picking.py

[FIX] udes_stock: Added missing decorator to picking create override

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_quant.py
addons/udes_stock/utils.py
addons/udes_transport_management/models/stock_picking.py
addons/udes_transport_management/models/transport.py

[ADD] udes_stock: Adding available qty in quant get info

---

addons/udes_transport_management/models/transport.py

This function should not exist here as it is preparing the data
in a format compatible for workflow. The function should exists
in a workflow controller.
User-story: 494

[FIX] udes_transport_management: Fix get transport info

---

addons/udes_get_info/models/models.py
addons/udes_get_info/models/stock_location.py
addons/udes_get_info/tests/test_get_info.py

[ADD] udes_get_info: Get info, Review usefulness and port

---

addons/udes_common/models/models.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/test_groupby.py

Groupby has been updated so it can correctly group with recordsets in a tuple. The code and unit tests have been ported from UDES 11. 
Story/901
Signed-off by: Jack Birch <jack.birch@unipart.io>

#901 Port UDES 11 groupby bug fix to UDES 14

---

addons/udes_stock/models/product_product.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_product.py

[IMP] udes_stock: Port over assert_serial_numbers() method from UDES11.
A unit test has been written to ensure the method runs as expected.
Story/1170
Signed-off by: Jack Birch <jack.birch@unipart.io>

Story #1170 Mobile UI: Product serial numbers validation 

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_scanned_by.py
addons/udes_stock/tests/test_stock_location.py

Add tracking data of who did the picking and the done datetime.
Add unit tests covering this.
User-story: 1083

[ADD] udes_stock: Add in "scanned by" functionality

---

addons/udes_suggest_location/models/stock_picking_type.py
addons/udes_suggest_location/registry/__init__.py
addons/udes_suggest_location/registry/suggest_by_empty_location.py
addons/udes_suggest_location/registry/suggest_by_product.py
addons/udes_suggest_location/registry/suggest_exactly_match_move_line.py
addons/udes_suggest_location/tests/__init__.py
addons/udes_suggest_location/tests/common.py
addons/udes_suggest_location/tests/test_suggest_by_empty_location.py
addons/udes_suggest_location/tests/test_suggest_exactly_match_move_line.py

[IMP] udes_suggest_location: Implement the ByEmptyLocation and ExactlyMatchMoveLine policies for the suggested location.
- Unit tests for both policies have been created.
- ByEmptyLocation and ExactlyMatchMoveLine policies are implemented
- ExactlyMatchMoveLine is set as the default policy as in UDES11
Story/54

Story #54 Suggested Locations: Ensure locations obey storage policies

---

addons/udes_stock/models/res_users.py
addons/udes_stock/models/stock_picking_batch.py

[ADD] udes_stock: Stub function for additional hooks

---

addons/udes_stock_picking_batch/README.md
addons/udes_stock_picking_batch/__manifest__.py
addons/udes_stock_picking_batch/models/stock_picking.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py
addons/udes_stock_picking_batch/models/stock_picking_type.py
addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py
addons/udes_stock_picking_batch/views/stock_picking_batch.xml

User-story: 1172
Implement additional batch states from UDES11 and relative
functions.

[IMP] udes_stock_picking_batch: Implement Batch States

---

addons/udes_stock_picking_batch/README.md
addons/udes_stock_picking_batch/__manifest__.py
addons/udes_stock_picking_batch/models/stock_picking.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py
addons/udes_stock_picking_batch/models/stock_picking_type.py
addons/udes_stock_picking_batch/tests/test_stock_picking.py
addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py
addons/udes_stock_picking_batch/views/stock_picking_type.xml

[ADD] udes_stock_picking_batch: Porting batch user managing.

---

addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py

[FIX] udes_stock_picking_batch: Fix units tests by renaming package.

---

addons/udes_stock/models/stock_picking_batch.py

Fixes the bug where the pallet is asked to be scanned again after
being dropped off in workflows.
User-story: 1827

[IMP] udes_stock: Ensure last reserved pallet is cleared on drop-off

---

addons/udes_stock/static/src/js/list_controller.js
addons/udes_stock/views/web.xml

[ADD] udes_stock: Warning message when mass (un)archiving

---

addons/udes_sale_stock/data/ir_cron.xml
addons/udes_sale_stock/data/stock_config.xml
addons/udes_sale_stock/models/sale_order.py

[ADD] udes_sale_stock: Merge Confirm Orders and  Reserve Stock Cron Job

---

addons/udes_security/static/src/js/relational_fields.js
addons/udes_security/views/webclient_templates.xml

[ADD] udes_security: Disable quick create by default on fields

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/data/branding_digest_tip_data.xml
addons/udes_sale_stock/views/branding_res_config_settings.xml

1670 Branding - Remove Odoo references

---

addons/udes_stock/data/stock_config.xml

[ADD] udes_stock: Enable product packaging

---

addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Adding reserve pallet on get_tasks

---

addons/udes_stock/models/stock_picking.py

Use SQL in favour of .mapped() and going via the ORM, which results
in costly joins/orderbys.
User-story: 1665

[FIX] udes_stock: Optimize u_next_picking_ids/u_prev_picking_ids

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock_picking_batch/models/stock_picking.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py

Sudo()s are being moved to inner functions in udes_stock. 
Story/1711
Signed-off-by: Jack Birch <jack.birch@unipart.io>

Story #1711 Mobile UI: port udes_workflows to UDES14 Outbound

---

addons/udes_warehouse_classification/models/product_template.py
addons/udes_warehouse_classification/models/stock_picking.py

[ADD] udes_warehouse_classification: Get warehouse classification

---

addons/udes_stock/__manifest__.py
addons/udes_stock/tests/test_limit_orderpoints.py

[FIX] udes_stock: Fix UTs and add dependency

---

addons/udes_stock/models/stock_picking.py

[FIX] udes_stock: Adding optional parameter on dummy method

---

addons/udes_simple_location_blocking/models/stock_location.py
addons/udes_simple_location_blocking/tests/test_location.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/test_stock_location.py
addons/udes_stock/views/stock_location_views.xml

Port the location state from 11 to 14. The only possible location states
are:
* empty
* archived
* has_stock
Blocked is currently not ported.
User-story: 2106

[ADD] udes_stock: Port location state

---

addons/udes_sale_stock/data/ir_cron.xml
addons/udes_stock/__manifest__.py
addons/udes_stock/data/picking_types.xml
addons/udes_stock/models/__init__.py
addons/udes_stock/models/res_config_settings.py
addons/udes_stock_picking_batch/models/stock_move_line.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py

[ADD] udes_stock_picking_batch: Adding reserve pallet on get_tasks

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/views/stock_picking.xml

[ADD] udes_stock: Date of transfer applies to cancelled pickings

---

addons/udes_stock/data/routes.xml

[FIX] udes_stock: Adding company on replen route

---

addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/tests/test_stock_picking_user_assignment.py
addons/udes_stock_picking_batch/tests/test_stock_picking.py
addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py

Correct permissions were implemented for users in the udes_open unit tests.

Story #2015 Improve tests common code of user permissions

---

addons/udes_stock/tests/common.py

[ADD] udes_stock: New serialised product in unit test baseclass

---

addons/udes_stock/models/res_users.py

[IMP] udes_stock: Overwrite the get_current_user_id method.
Story/2168
Signed-off-by: Jack Birch <jack.birch@unipart.io>

Story #2168 Move Cancellation message to show partially cancelled qtys correctly

---

addons/udes_stock/data/picking_types.xml

[IMP] udes_stock: Allow Stock Move to move from any location

---

addons/udes_stock/__manifest__.py
addons/udes_stock/data/locations.xml
addons/udes_stock/static/src/js/form_controller.js
addons/udes_stock/views/assets.xml
addons/udes_stock/views/stock_location_views.xml
addons/udes_stock_inventory/README.md
addons/udes_stock_inventory/__init__.py
addons/udes_stock_inventory/__manifest__.py
addons/udes_stock_inventory/models/__init__.py
addons/udes_stock_inventory/models/product_product.py
addons/udes_stock_inventory/models/stock_inventory.py
addons/udes_stock_inventory/views/stock_inventory_views.xml

Descriptions in the individual commits.

Story/2466 - Inventory Adjustment overhaul and various changes/improvements for UDES

---

addons/udes_stock/tests/test_stock_picking.py

[FIX] udes_stock: Code typo in UTs fix

---

addons/udes_common/models/models.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/test_prevent_bad_dates.py

[ADD] udes_common: Prevent dates in backend when year is less than 1000

---

addons/udes_stock/models/models.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_prevent_bad_dates.py

Entered year should be more than year 1000
Story: 2390

[ADD] udes_stock: Checking in backend date fields

---

addons/udes_stock_inventory/models/stock_inventory.py
addons/udes_stock_inventory/views/stock_inventory_views.xml

Rename description on `stock.inventory`, add default ordering for `is_editable` for `stock.inventory.line`.

Minor Inventory Adjustment improvements.

---

addons/udes_sale_stock/views/sale_order_views.xml

[IMP] udes_sale_stock: Move the requested date to the main section of the sale order form.
Story/2436
Signed-off-by: Jack Birch <jack.birch@unipart.io>

Story #2436 UI - Sales Order Delivery Date

---

addons/udes_stock/models/models.py

[FIX] udes_stock: Not filtering date fields shorter than 10 chars

---

addons/udes_common/models/models.py

[FIX] udes_common: Not filtering date fields shorter than 10 chars

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

[ADD] udes_stock: Add count package/ pallet flags

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py
addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py

Story: x2764
Signed-off-by: Lorenzo Cucurachi <lorenzo.cucurachi@unipart.com>

[IMP] udes_stock: Block deletition of pickings outside draft state

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_stock_move_line.py
addons/udes_stock/views/stock_picking_type.xml

- Backend changes to allow for tracked products to be swapped in/out
- Tests for the Changes

Story #2657 Mobile UI: Allow swaps for tracked products at Pick

---

addons/udes_common/models/models.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/common.py
addons/udes_common/tests/test_groupby.py
addons/udes_common/tests/test_record_is_child_of_self.py
addons/udes_stock/README.md
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_move.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/views/stock_picking.xml
addons/udes_stock_refactoring/models/stock_picking.py
addons/udes_stock_refactoring/tests/test_refactoring.py

Take into account package links when refactoring pickings

Story/2911 - Refactoring with package links

---

addons/udes_sale_stock/tests/test_sale_order.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_stock_move.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/tests/test_stock_warehouse.py
addons/udes_suggest_location/tests/common.py
addons/udes_suggest_location/tests/test_stock_move.py
addons/udes_suggest_location/tests/test_stock_move_line.py
addons/udes_suggest_location/tests/test_suggest_by_product.py

- Adjusted the outbound route in UnconfiguredBaseUdes to include Trailer Dispatch
- Created another base test class BaseUDESPullOutboundRoute, which has a outbound route that will pull from stock
- Implemented the "Check" picking type in UnconfiguredBaseUdes and added it to the outbound route

Story #2888 UDES 14 - UnconfiguredBaseUdes does not have Trailer Dispatch route

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/utils.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py

Story: x1666
Signed-off-by: Lorenzo Cucurachi <lorenzo.cucurachi@unipart.com>

[IMP] udes_stock, udes_stock_picking_batch: Add logging for monitor

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/utils.py

Add logging for action_done, mark_as_done and drop_off_picked.
These will be used by the UDES monitor to generate stats and present
these to our developers.

[IMP] udes_stock: Add logging for monitoring

---

addons/udes_stock/static/src/js/form_controller.js

Check removed from earlier commit after rebasing error.
Signed-off-by: Peter Clark <peter.clark@unipart.com>

[FIX] udes_stock: Check for create button before attempting to hide it

---

addons/udes_security/controllers/main.py

Signed-off-by: Peter Alabaster <peter.alabaster@unipart.com>
User-story: 3029

[FIX] udes_security: Handle javascript `do_action("extid")` properly

---

addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Setting destination location on split

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_move_line.py

- A more detailed error message with information on the move lines in the "done" state are given
- Unit tests were added to test the error message
- Formatting
User-story: 3033
Signed-off-by: Jack Birch <jack.birch@unipart.com>

story #3033 Picking - Improve error messaging/logging when picking can't be validated

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_stock_move_line.py

- Add messages to thread of picking showing tracked products were swapped
- Update unit tests for different edge cases

#3076 Swapped sn/lot details at bottom in log section

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py
addons/udes_stock/views/stock_picking.xml

- Added a unit test to check updates to the source document are added to the message thread
User-story: 3206
Signed-off-by: Jack Birch <jack.birch@unipart.com>

[IMP] udes_stock: Make source document field editable outside 'draft'.

---

addons/udes_delivery_control/views/stock_picking.xml

[ADD] delivery_control: Pickings with no partners able to be cancelled

---

addons/udes_security/models/models.py
addons/udes_stock/views/product_template.xml

- Remove deprecated overwrite in view
- Reword archive/unarchive message

story #3207 Product - Reword warning message when archiving/unarchiving products

---

addons/udes_stock/models/stock_move.py
addons/udes_stock_cron/models/stock_picking.py
addons/udes_stock_refactoring/models/stock_move.py
addons/udes_stock_refactoring/tests/test_refactoring.py

[FIX] udes_stock_refactoring: Refactor partial moves correctly.

---

addons/udes_stock/models/stock_quant.py

[ADD] udes_stock: Splitting get_move_lines domain on its own method

---

addons/udes_stock/models/stock_warehouse.py

[ADD] udes_stock: Adding a config for current quantity on wharehouse

---

addons/udes_stock/wizard/stock_picking_to_batch_views.xml

[ADD] udes_stock: Access right to outbound user to add picking to batch

---

addons/udes_security/README.md
addons/udes_security/__manifest__.py
addons/udes_security/models/__init__.py
addons/udes_security/models/res_company.py
addons/udes_security/models/res_users.py
addons/udes_security/tests/__init__.py
addons/udes_security/tests/common.py
addons/udes_security/tests/test_desktop_access.py
addons/udes_security/tests/test_password_complexity.py
addons/udes_security/views/res_company_view.xml

[IMP] udes_security: Add password complexity.

---

addons/udes_stock/tests/test_utils.py
addons/udes_stock/utils.py

Signed-off-by: Peter Alabaster <peter.alabaster@unipart.com>
User-story: 3622

[FIX] udes_stock: Update util for product images to work in 14.0

---

addons/udes_stock/__manifest__.py
addons/udes_stock/views/stock_location_route_views.xml

[ADD] udes_stock: Show archived rules on route

---

addons/udes_stock/__manifest__.py
addons/udes_stock/views/stock_location_route_views.xml

[ADD] udes_stock: Show archived rules on a route

---

addons/udes_stock/models/stock_quant_package.py

- `find_move_lines` now return move lines for parent packages

Story #2298 Rockhopper/Gentoo - Check into a Pallet

---

addons/udes_stock/models/stock_location_route.py
addons/udes_stock/views/stock_location_route_views.xml

[ADD] udes_stock: Visibility of archived rules for procurement routes

---

addons/udes_stock/models/stock_picking.py

- Context should be extended instead of overwritten

Fix where the context should be extended instead of overwritten

---

addons/udes_stock/models/stock_move.py

- Add a context flag to skip refactoring

Story #4035 Desktop backorder refactoring bug

---

addons/udes_stock/models/product_product.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_product.py

with different quantities
Story: 3427

[IMP] udes_stock: Improve mark_picked_lines to handle multiple lots

---

addons/udes_stock/tests/test_stock_picking.py

- Odoo-tester image has been updated for CI
- Unit test skip has been removed

Story #3619 CI - Unskip test

---

addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/tests/test_stock_warehouse.py

[ADD] udes_stock: Ignoring picking types to be updated

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock_refactoring/models/stock_move.py
addons/udes_stock_refactoring/models/stock_picking_type.py
addons/udes_stock_refactoring/registry/__init__.py
addons/udes_stock_refactoring/registry/refactor_by_maximum_quantity.py
addons/udes_stock_refactoring/tests/test_refactoring.py

[ADD] udes_stock,udes_stock_refactoring: Migrating refactoring by quantity

---

addons/udes_stock_refactoring/README.md

story/4169
Document `u_assign_refactor_constraint_value` in the README.

[DOC] udes_stock_refactoring: Document picking type attribute.

---

addons/udes_stock_picking_batch/models/stock_move_line.py

Add sum of initial quantities to the task

User-story: 4569

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_stock_move_line.py
addons/udes_stock_picking_batch/models/stock_picking_batch.py

[ADD] udes_stock: Merging move lines

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock_picking_batch/models/stock_move_line.py

- Updating various parts of the backend code to handle floats

Story #4725 UDES 14 - All flows to handle floats

---

addons/udes_stock_picking_batch/views/stock_picking.xml

[IMP] udes_stock_picking: Add current batch to stock picking form screen

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

[ADD] udes_stock: Adding regexes to picking types

---

addons/udes_stock_picking_batch/models/stock_move_line.py

- Store extra information about a tasks `result_package_id` for later processing

[IMP] udes_stock_picking_batch: Retrieve information about a tasks result_package_id.

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock_refactoring/models/stock_picking.py

[ADD] udes_stock: Setting original picking id when refactoring

---

addons/udes_stock_picking_batch/tests/test_stock_picking_batch.py

[FIX] udes_stock_picking_batch: fix failing unit test

---

addons/udes_stock_refactoring/models/common.py
addons/udes_stock_refactoring/tests/test_refactoring.py

adding more coverage on refactoring unit test by adding more test cases in testbydate and testbydatepriority class.
Story :: SET/154
Sign off By :: vishal.vasoya@unipart.com

[Refactor] - More coverage on Refactoring Unit tests

---

addons/udes_stock/tests/common.py

[ADD] udes_stock: Possibility to create lot or packages on specific user

---

addons/udes_warehouse_classification/wizard/add_product_classification.py

Add _description to wizard to prevent warning

[META] udes_warehouse_classification: Fix warning

---

Dockerfile
addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Write destination location before qty done when picking the items

---

addons/udes_stock/models/product_product.py
addons/udes_stock/models/product_template.py

[IMP] udes_stock: Change the tracking of a product if it has no stock

---

addons/udes_stock/models/stock_move_line.py

Ensure that the remaining quantity is correctly calculated and rounded when picking decimal quantities.

[FIX] udes_stock: Rounding errors when receiving decimals

---

addons/edi_notifier/models/notifier.py

[ADD] edi_notifier: Getting action with sudo

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_move_line.py

- Update methods to handle over receiving / unexpected products

Add Unexpected Items

---

addons/udes_stock/models/stock_picking.py

This allows other modules to extend the function to modify an individual
moves values based on product_info.
SE-928

[ADD] udes_stock: Abstract individual move value prep to function

---

addons/udes_common/tools/statistics.py

[FIX] udes_common: Use higher-precision function to measure statistics

---

addons/udes_security/models/mail_thread.py

[FIX] udes_security: mail thread could be html in binary form, fix comparison

---

addons/udes_common/__manifest__.py
addons/udes_common/models/fields.py
addons/udes_common/static/src/js/core/time.js
addons/udes_common/static/src/js/fields/field_utils.js
addons/udes_common/static/src/js/precisedatetime_fields.js
addons/udes_common/views/assets.xml

[ADD] udes_common: JS files to display precise datetime field

---

addons/udes_stock/tests/common.py
addons/udes_stock_cron/tests/test_stock_picking.py

[ADD] udes_stock: Patching cursor not to commit changes

---

addons/udes_stock/models/stock_move_line.py

SE-1409
When working with fields that define "Product Unit of Measure" as their _digits attribute we should use odoo's float tools when comparing values so that rounding and floating-point inaccuracies are taken into account.

[FIX] udes_stock: Consider rounding when checking for incomplete lines

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py

[IMP] stock_picking_batch:  disable_move_refactor in unpickable_item()

---

addons/udes_stock/models/procurement.py
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py

[ADD] udes_stock: Transfer create procurement group on stock move 

---

addons/edi_sale_notifier/models/edi_sale_request_document.py

[ADD] edi_sale_notifier: Renaming method

---

addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: Update Kanban view layout for 'Draft' counts

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock_routing/__manifest__.py
addons/udes_stock_routing/models/__init__.py
addons/udes_stock_routing/models/stock_location.py
addons/udes_stock_routing/models/stock_move.py
addons/udes_stock_routing/models/stock_picking.py
addons/udes_stock_routing/tests/__init__.py
addons/udes_stock_routing/tests/test_two_stage_outbound.py
addons/udes_stock_routing/views/stock_location_views.xml

[ADD] udes_stock_routing: Two stage outbound hook

---

addons/udes_stock/__init__.py
addons/udes_stock/__manifest__.py
addons/udes_stock/security/ir.model.access.csv
addons/udes_stock/wizard/__init__.py
addons/udes_stock/wizard/stock_picking_mark_todo.py
addons/udes_stock/wizard/stock_picking_mark_todo_views.xml

[ADD] udes_stock: Mark As TODO multi pickings at once

---

addons/udes_stock_packaging/__manifest__.py
addons/udes_stock_packaging/models/__init__.py
addons/udes_stock_packaging/models/container_type.py
addons/udes_stock_packaging/security/ir.model.access.csv
addons/udes_stock_packaging/tests/__init__.py
addons/udes_stock_packaging/tests/test_container_types.py
addons/udes_stock_packaging/views/container_type_views.xml

[ADD] SE-1746 udes_stock: Container Type Model and View

---

addons/udes_stock_refactoring/README.md
addons/udes_stock_refactoring/models/stock_move.py
addons/udes_stock_refactoring/models/stock_picking_type.py
addons/udes_stock_refactoring/registry/__init__.py
addons/udes_stock_refactoring/registry/refactor_by_maximum_weight.py
addons/udes_stock_refactoring/tests/test_refactoring.py
addons/udes_stock_refactoring/views/stock_picking_type_views.xml

Original MR: https://github.com/unipartdigital/udes-open/pull/884
Reworked to be based on moves instead of move lines, and support post confirm also.

Se 1752 2 Refactor by weight

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/views/sale_order_views.xml
addons/udes_sale_stock/views/udes_carrier_views.xml

[IMP] udes_sale_stock: Added Carriers menu and view

---

addons/udes_stock/tests/common.py

Ensures that the correct location target storage format is used for receive locations.

[TEST] udes_stock: Reset received location storage format

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/models/stock_picking.py
addons/udes_sale_stock/models/stock_picking_type.py
addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/common.py
addons/udes_sale_stock/tests/test_full_sale_reservation.py
addons/udes_sale_stock/views/stock_picking_type_views.xml
addons/udes_stock_cron/models/stock_picking.py

[ADD] udes_sale_stock, udes_stock_cron: Full sale reservation

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/stock_picking.py
addons/udes_sale_stock/views/sale_order_views.xml
addons/udes_stock/models/stock_picking.py
addons/udes_stock_packaging/__manifest__.py
addons/udes_stock_packaging/models/stock_picking.py
addons/udes_stock_packaging/models/stock_quant_package.py
addons/udes_stock_packaging/views/stock_quant_package.xml

SE-1747 [ADD] u_tracking_id, u_container_type to udes_stock_packaging

---

addons/udes_stock_refactoring/models/stock_move.py
addons/udes_stock_routing/models/stock_move.py
addons/udes_stock_routing/models/stock_picking.py

SE-1812 Fix empty pickings.

---

addons/udes_stock_packaging/models/stock_quant_package.py

[ADD] udes_stock_packaging: Check package contains single item method

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py

[ADD] udes_stock: Backorder when multi users is enabled

---

addons/udes_stock_packaging/models/container_type.py

Specifically when use_product_dims is True
SE-1922

[IMP] udes_stock_packaging: Box dims can now be 0

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: New field u_total_weight added in the Picking model

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/tests/test_sale_order.py
addons/udes_sale_stock/views/sale_order_views.xml

[IMP] udes_sale_stock: Add 'Done Date' field to Sales Order

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py

[IMP] udes_stock: Adding updating move line functionality and related functionality to udes_stock

---

addons/udes_stock/models/mixin_stock_model.py
addons/udes_stock_packaging/__manifest__.py
addons/udes_stock_packaging/data/package_types.xml
addons/udes_stock_packaging/models/__init__.py
addons/udes_stock_packaging/models/package_type.py
addons/udes_stock_packaging/models/stock_picking_type.py
addons/udes_stock_packaging/models/stock_quant_package.py
addons/udes_stock_packaging/security/ir.model.access.csv
addons/udes_stock_packaging/tests/test_stock_quant_package.py
addons/udes_stock_packaging/views/package_type_views.xml
addons/udes_stock_packaging/views/stock_quant_package.xml

[ADD] udes_stock_packaging: Adding package type

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_move_line_views.xml
addons/udes_stock/views/stock_picking.xml
addons/udes_stock/views/stock_picking_type.xml

When use multiple measures config is enabled.
SE-1983

[ADD] udes_stock: Pick by multiple measures functionality 

---

addons/udes_stock/models/product_product.py
addons/udes_stock/models/stock_move_line.py

[ADD] udes_stock: Mark move lines as done without lot information

---

addons/udes_security/models/ir_attachment.py

[IMP] udes_security: No longer process images with addons

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_stock_move_line.py
addons/udes_stock_routing/models/stock_move.py

[IMP] udes_stock: Set done qty on move lines via a loop

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_stock_move_line.py

[FIX] udes_stock: Allow total qty scan for lots

---

addons/udes_stock_refactoring/models/stock_picking.py
addons/udes_stock_refactoring/tests/test_refactoring.py

[ADD] refactoring:  Copying sequence field when moves are refactored

---

addons/udes_stock_refactoring/models/stock_move_line.py

Recomputing u_grouping_key every time method group_by_key is called.
SE-2119

[ADD] udes_stock_refactoring: Recomputing u_grouping_key every

---

addons/udes_stock/models/product_product.py
addons/udes_stock/models/stock_warehouse_orderpoint.py

Add/Remove replen route on products based on their replenishment rules
SE-2156

[IMP] udes_stock: UDES14 Product replen flag

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/models/__init__.py
addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/sale_order_line.py
addons/udes_sale_stock/models/stock_location_route.py
addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/test_sale_order_delivery_status.py
addons/udes_sale_stock/views/sale_order_views.xml
addons/udes_sale_stock/views/stock_location_route.xml

[ADD] udes_sale_stock: Create a new status for sale orders
