addons/udes_stock/__manifest__.py
addons/udes_stock/report/product_product_templates.xml
addons/udes_stock/report/report_stockpicking_operations.xml

Default stock/product reports use EAN8 and EAN13 encodings by default
when length of the barcode is 8 or 13 respectively, otherwise it uses
code128. In some cases the barcodes of length 8 are not compatible with
EAN8, therefore we override it to always use code128.

[FIX] udes_core: always use code128 for product barcodes

---

addons/udes_stock/models/stock_move_line.py

Here we fix the way package pick operations are validated.
This is now necessary as the frontend logic implements
paletless pick for packages.

[FIX] Palletless Pick: fix validation

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_update_picking.py

Products tracked by lot should be able to use the same lot number when
receiving stock, either because they are in the different packages or
because they are received in different transfers.
This is related to Odoo core fix:
f7715e18aa8a159ddd48c46c65de7a821ffe6c52

[IMP] udes_stock: Allow to use same lot twice

---

addons/udes_stock/views/stock_picking.xml

XPath expressions must not use human-readable text strings to locate
elements to be modified since these are likely to be changed.  In
particular, the expression will fail if it refers to a text string
subject to language translation.
Fix by matching on the "name" attribute value (and absence of the
"context" attribute) instead of matching on the element text contents.

[FIX] udes_stock: Do not use translatable strings in xpath expressions

---

addons/udes_sale_stock/models/sale_order.py

By default when canceling a sale order, sale_stock module cancels the
related stock.pickings, but when several orders share pickings that
ends up canceling stock.moves of other sale orders.
This is addressed by canceling by stock.moe instead of stock.picking.

[FIX] udes_sale_stock: Cancel related moves on sale.order.action_cancel()

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_picking_type.py
addons/udes_stock/views/stock_location.xml
addons/udes_stock/views/stock_picking_type.xml

Add the ability to preprocess suggested locations and add them to a move line
this allows the location to effectively reserved (for policies which check for this).
Also implements a policy to suggest locations based on height/speed category and also doing the aforementioned check

story/1688: Putaway suggestions preprocessing

---

addons/udes_stock/models/__init__.py
addons/udes_stock/models/stock_location_path.py
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_push_from_drop.py
addons/udes_stock/tests/test_splitting.py

In order to allow stock to be diverted to a "Damaged" location in
Inbound if a damaged pallet is received, push rules can now be triggered
by dropping stock into a location from which a push rule originates.
If such a rule exists when dropping stock, a new set of moves are
created, linked back to the moves that dropped the stock into that
location, and reserved, which in turn creates the rest of the push
route.
This allows for routes to fork, or to merge (untested) by dropping into
a location.
This behaviour can be disabled with a flag on the push rule.
Story: 1775

WiP: [IMP] udes_stock: Push stock from a drop location.

---

addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/common.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_move_line.py
addons/udes_stock/tests/test_update_picking.py

The constraint is also now triggered by onchange and checks if the
location is one of the suggested locations when the drop off constraint
is set to enforce at the picking type.

[IMP] udes_stock: Extend stock.move.line location_dest_id constraint

---

addons/udes_stock/models/stock_move.py

Allow a refactoring method to return None to indicate that the set of
move lines has remained unaltered.  This allow for simpler code when
the move lines are not themselves being modified, and eliminates some
unnecessary recordset manipulation.

[IMP] udes_stock: Allow refactoring methods to return None

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py

[FIX] udes_stock: Copy move_dest_ids when splitting moves

---

addons/udes_stock/models/stock_picking.py

This function is now also used with pickings in state different than
available.

[FIX] udes_stock: Improve search at _new_picking_for_group()

---

addons/udes_stock/__manifest__.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/views/stock_picking_batch.xml

Add a requested_date fields to stock.picking.batch, calculated as the
earliest requested date of any constituent stock.picking.

[IMP] udes_stock: Add stock.picking.batch.requested_date field

---

addons/udes_stock/models/stock_picking_batch.py

Batches created automatically in pick should be ephemeral so that pickings are unassigned when the user logs out or goes on break.

[FIX] udes_stock: Auto created batches in pick should be ephemeral

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py

Adding the move lines result package barcodes to the
batch metadata returned in the batch::get response.
This can be then used by the requester to easily
determine whether a scanned pallet barcode is expected
by the batch.
Task: 2165

[ADD] Result package information to batch::get

---

addons/udes_stock/models/stock_picking.py

Since move lines might change because of refactoring the recordset
has to be updated using .exists().
User-story: 2180

[FIX] udes_stock: Update move lines after calling stock.picking.super.action_done()

---

addons/udes_stock/models/stock_picking.py

This solves the issue where some move lines were losing the result
parent package when they were coming from different pickings and
refactored into one.
Issue: 2606

[FIX] udes_stock: Check entire packages after refactoring moves

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_splitting.py

In some cases the function was returning a log error like:
Comparing oranges and apples.
The issue was that when there is already an existing picking that
matches for the given group, some fields are checked to see if
their current value is consistent with the new one to update.
If it is not then the value of the picking is set to False to avoid
misleading information. When this happens the values sometimes are
the id of the res.partner, or another recordset. In that case we
were ending up comparing a recordset with an integer.
Fixed to get the id of the recordset instead.

[FIX] udes_stock: Fix new_picking_for_group()

---

Dockerfile
addons/udes_security/__init__.py
addons/udes_security/__manifest__.py
addons/udes_security/data/auth_brute_force.xml
addons/udes_security/models/__init__.py
addons/udes_security/models/res_authentication_attempt.py

Adding auth_brute_force (from server_auth) module as a udes_security
dependency. Adding default configs for the modules inbuilt settings
and adding an additional setting to allow us to disable the global
IP ban for all users - allowing this to be used with Odoo when
x_forwarded_for headers are not available when behind a proxy.

[IMP] udes_security: Enabling auth_brute_force module with settings

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking.py

The state of a picking with partially available moves is going to
be 'waiting' or 'confirmed' instead of 'assigned' when the
value of u_handle_partials of its picking type is False, because
it means that the picking cannot be worked with until it is fully
assigned.
Issue: 2502

[IMP] udes_stock: Override stock.picking._recompute_state()

---

addons/udes_stock/report/report_goods_slip.xml

Many scanners by default do not scan single digit Code128 barcodes.
Padding the quantities makes the barcode more likely to be
scannable by default.

[FIX] udes_stock: Goods slip qty barcode to have preceeding zeroes

---

addons/udes_stock/controllers/stock_picking.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_splitting.py
addons/udes_stock/wizard/refactor_views.py

To ensure that any system generated canceled pickings are deleted
so that the system does not pollute the database with empty data.

[FIX] udes_stock: Unlink empty pickings after refactoring

---

addons/udes_sale_stock/models/partner_pii.py

Logging PII accesses for the superuser adds substantial amounts of log
noise and increase the time (and therefore cost) required to diagnose
almost any problem.
The superuser may be assumed to have full access to the system,
including the ability to tamper with the log files.  In addition,
security policy dictates that administrators log in as individual
accounts with administrative permissions, rather than logging in as
the superuser account.

[FIX] udes_sale_stock: Bypass PII view logging for the superuser

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking.py

Pick factorisation may result in some empty pickings.  The current
code attempts to cancel these by directly writing the "state" field to
the value "cancel", with a comment noting that action_cancel() does
not work on a picking with no associated stock moves.
The reason that action_cancel() does not work on a picking with no
associated stock moves is that the "state" field is a readonly field
computed from the associated stock move lines.  A picking with no
associated stock move lines is, by definition, in state "draft".
The current code seems to succeed in setting the state to "cancel" due
only to the permissiveness of the ORM, which (for performance reasons)
generally trusts code not to attempt undefined operations such as
writing to a non-invertible but stored computed field.
Fix by …

[FIX] udes_stock: Do not attempt to cancel empty pickings

---

addons/udes_report/data/stock_email.xml

[FIX] udes_report: fix typo in scheduled action title

---

addons/udes_sale_stock/models/sale_order_line.py
addons/udes_sale_stock/models/stock_move.py

Using api onchange is inefficient, it will calcualte for every state
change. Set this only when cancelling the final picking.

[FIX] udes_sale_stock: Set sale_line is_cancelled on picking.action_cancel

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/security/udes_stock_security.xml

The improvements come because of two changes:
The first is removing the or branch in the domain a db query is removed.
The second is done by storing the picking type directly on the move_line
which removes an unbound query on the moves.
Credit goes Miquel who came up with the fix.

[IMP] udes_stock: Improve evaluation speed of move/move_line access rules

---

addons/udes_stock/models/stock_picking.py

Include any locations with no speed or height categorisation within
the suggested location search.  This allows for the existence of
generic locations that are, for example, allowed to hold products of
any speed.

[IMP] udes_stock: Allow for uncategorised putaway locations

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_package_reservation.py

Fix a bug when action_assign is called on more than one picking
at a time, with package reservation turned on.
The bug was caused by erroneous use of self while in a loop over
the records in self, causing all packages in all pickings in self
to have to be in the current item of the loop.
This fixes the issue and adds a unit test.
Story: 3453

[FIX] udes_stock: Fix package reservation for multiple pickings

---

addons/udes_sale_stock/__manifest__.py

`udes_sale_stock` defines a `SaleOrder._order` attribute that references a
field defined in `sale_order_dates`, so `udes_sale_stock` needs to depend on
this module.
User-story: 3621
Task: 3622

[FIX] udes_sale_stock: depend on sale_order_dates

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/data/stock_config.xml
addons/udes_stock/__manifest__.py
addons/udes_stock/data/stock_config.xml

udes_stock had an incorrect dependency on sale_stock, in order
to set a config option. This was incorrect and causes 15 extra
modules to be installed on the mvp system, significantly increasing
risk and cost of maintainance.
This change moves the dependency and config into the udes_sale_stock
module, which houses our other work that depends on sale_stock.
Story: 3390

[FIX] udes_stock, udes_sale_stock: Correct dependency and config

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_print_strategy.py
addons/udes_stock/views/stock_picking_print_strategy_views.xml

Here we send information about where the invocation
of the printing run method (that checks strategies)
is performed. We also gather more context info by
invoking a subclass method if defined.
The reason for that is to enable more control around
what strategies should be used for different picking
types.
User-story: 3598
Epic: 3584

[ADD] used_stock (3598) more control over printing

---

addons/udes_stock/models/stock_move_line.py

This allows hooks into the printing triggers
User-story: 4019
Epic: 3584

[REF] udes_stock: Refactor printing in move_line mark_as_done

---

addons/udes_security/__manifest__.py
addons/udes_security/data/res_groups.xml
addons/udes_security/models/__init__.py
addons/udes_security/models/res_groups.py
addons/udes_security/models/res_users.py
addons/udes_stock/wizard/reservation_views.py
addons/udes_stock/wizard/reservation_views.xml

To match the behaviour of the existing Reserve Stock button, the new
Unreserve Stock button only affects pickings in the assigned state and
does nothing for all other pickings.
The button is only visible to users who have the Bulk Unreserve User
permission, which can only be granted in developer mode.
Task: 4086
User-story: 3917

[ADD] udes_stock: add button to bulk unreserve pickings

---

Dockerfile

We're currently downloading server-auth from Odoo 12.0. This fixes that
so we explicitly download version 11.0 to avoid getting pulled up a
version by whatever the OCA set as their default branch.
Task: 4208

[FIX] Dockerfile: correct version of server-auth

---

addons/udes_security/__init__.py
addons/udes_security/models/res_users.py
addons/udes_security/tests/__init__.py
addons/udes_security/tests/test_trusted_user.py

[FIX] udes_security: Fix Trusted User write check
Fix the res.users write override to correctly handle all many2many write
operations. Also remove the assumption that many2many write operations have
the right number of elements and no more.
Task: 4209
User-story: 3917
[ADD] udes_security: Add tests for restrictions on granting Trusted User
Task: 4209
User-story: 3917

[FIX] udes_security: Fix Trusted User write check and add tests

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_location_category.py

Remove dependency to location.u_location_category_id from
stock.picking.u_location_category_id to avoid conflicts.
Once it is set, it only changes if the move_lines or their
locations change.
This prevents to update it when pickings are done or serialisation
erros because they are in use.

[IMP] udes_stock: Revise stock.picking.u_location_category_id dependency

---

addons/udes_stock/tests/test_picking_batch.py

When going to add a unit test I noticed that this test was failing, so aim of this PR is to fix the failing tests in this file.
The changes that I made are:
* When marking a picking as done the "location_dest_id" of the pick needs to be set as the location that the product is moving to. Previously this was not being set and it was using "Output" which is a view not a valid location
* When a pick contains an unpickable item the location the picking_type_id field is being set to "Stock Investigation", previously it was "Internal"
Task: 4112

[FIX] Fixes for failing unit test - test_picking_batch

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_picking.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py

Do not update pickings when doing a GET call. This can cause several
problems, for instance when trying to get info of a picking in state
done.
User-story: 3753

udes_stock: Remove auto-batching from GET controller and add new policy by order point

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_limit_orderpoints.py
addons/udes_stock/views/stock_location.xml

Story/3885
This patch adds a boolean flag to the location model.  If set, the flag
prevents having more than one orderpoint on a location.

[IMP] udes_stock: Prevent locations having more than one orderpoint.

---

addons/udes_stock/models/stock_location.py

When the package is created but still without content the location
in self is different than the pallet location. This happens
when mulitple products of the same picking go into the same pallet,
because the location of the pallet is undefined.
User-story: 4604

[IMP] udes_stock: Fix stock.location.is_compatible_package

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_batch_pickings.py

Add a refactor action to allow pickings to be grouped in draft batches.
A generic method allows methods to be written to group by an arbitrary
key function. Specific actions allow picks to be grouped by date or by
date and priority.
User-story: 4543

[ADD] udes_stock: Refactor action to group pickings

---

addons/udes_stock/README.md
addons/udes_stock/data/picking_types.xml
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

Add a flag to PickingType to enable exception handling.
This flag is disabled by default and enabled explicitely for Pick
picking type.
User-story: 4743

[ADD] udes_stock: flag to enable exception handling

---

Dockerfile
addons/udes_security/__manifest__.py

The auth_session_timeout module times out user sessions after a
configurable duration, which is 2 hours by default.
Task: 4787
User-story: 98

[ADD] udes_security: Add dependency on auth_session_timeout

---

addons/udes_mrp/__init__.py
addons/udes_mrp/__manifest__.py
addons/udes_mrp/models/__init__.py
addons/udes_mrp/models/stock_picking.py
addons/udes_mrp/tests/__init__.py
addons/udes_mrp/tests/test_mrp_production.py
addons/udes_mrp/views/mrp_production_views.xml

Since they already show as waiting, it was requested that they do not show as todo.
Story: 4344
Task: 4716
Signed-off-by: Przemysław Buczkowski <pbuczkowski@unipart.io>

[IMP] mrp: make waiting Manufacturing Orders not show as todo

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/models/__init__.py
addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/stock_warehouse.py
addons/udes_sale_stock/views/stock_warehouse.xml
addons/udes_stock/views/stock_warehouse.xml

Adding config and functionality to automatically confirm sale orders
based on an x days in the  future value. Triggers so.action_confirm()
on all orders within x days (0 being today only)
Also adding a string to the UDES stock warehouse configs for clarity.

[IMP] udes_sale_stock,udes_stock: Adding auto-confirm for sale orders

---

addons/udes_sale_stock/models/sale_order.py

The check_delivered function did not account for a mixed terminal
state sale order, this has been addressed by confirming an order as
done when it's terminal pickings (i.e. all the last pickings in a
chain) are in a terminal state (done or cancelled).
User-story: 4516

[ADD] udes_sale_stock: Improve characterisation of sale order state

---

addons/udes_stock/tests/test_move.py

Tests for cancelling partially complete moves.
Task: 8967
From: unipartdigital/odoo#54

[ADD] udes_stock: tests for Move._action_cancel

---

addons/udes_stock/models/procurement.py

Calling unlink_empty() at procurement.group.run() causes to unexpectedly
being called when calling _procure_orderpoint_confirm().
This can cause serialisation errors if run() is triggered by more than
one reason at the same time, for example check reorder points and
procurement route creation.
There is a cron job to tidy up empty pickings which can be used instead.

[REM] udes_stock: Unneeded call to Picking.unlink_empty() at procurement.group

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/tests/test_batch_pickings.py
addons/udes_stock/tests/test_picking_batch.py

Recomputing the batch AFTER the picking cancel logic prevents quant
re-reservation being triggered on something that in in process of
being cancelled, and resolves the issue of batch-cancelled picks
still having reserved stock.

[FIX] udes_stock: Don't recompute batch on picking cancel until done

---

addons/udes_stock/models/product_template.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/test_location_pi.py

Allow stock check for locations containing products with the wrong lot number tracking type. Will still complain if a user attempts to stock new check items that are badly formed.
User-story: 9247

[IMP] stock_mobile: Allow stock check for locations with bad tracking

---

addons/udes_edi/__init__.py
addons/udes_edi/__manifest__.py
addons/udes_edi/security/edi_security.xml

Allow only trusted users to see the Raw Import EDI option in the UI to help
maintain data integrity.

[ADD] udes_edi: Add udes_edi to udes-open

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_picking_batch.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/tests/test_picking_batch.py
addons/udes_stock/views/stock_picking_batch.xml

[ADD] udes_stock: Add reserve_pallet functionality for batches
reserve_pallet reserves a single pallet for use in a batch and raises
an error if another batch has already reserved the pallet. Pallets are
automatically considered unreserved once the batch is done or a different
pallet is reserved for the batch.
User-story: 9391

[ADD] udes_stock: Add reserve_pallet functionality for batches

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py

Overriden _set_u_result_parent_package_id to not add parent package
if the u_target_storage_format is a package/pallet of packages,
this facilitates correctly storing as packages in pick face from
returns putaway/internal transfer.
User-story: 9570

[IMP] udes_stock: Override _set_u_result_parent_package_id

---

addons/udes_stock/models/stock_quant_package.py
addons/udes_stock/tests/test_package_hierarchy.py

Calculate depth and validate against max package depth on the fly,
instead of storing depth value against packages. (task/9748)

[FIX] udes_stock: Package hierarchy depth and constaint on the fly

---

addons/udes_load_testing/README.md

User-story/9878
Task/9985
Calling `_report()` in a test method means that it gets counted as a test,
and triggers the class's `setUp()` method.  Recommend that it be called
in the class's `tearDown` method instead.

{IMP] udes_load_testing: recommend running _report in tearDown

---

addons/udes_load_testing/README.md
addons/udes_load_testing/tests/common.py

User-story/9878
So spreadsheet applications open them correctly.

[IMP] udes_load_testing: Output files should have .tsv extension

---

addons/udes_security/controllers/redirect.py
addons/udes_security/data/res_groups.xml
addons/udes_security/data/res_users.xml
addons/udes_security/models/res_groups.py
addons/udes_security/models/res_users.py
addons/udes_security/tests/test_trusted_user.py

Added a 'debug user' group that can only be added to by the main admin user, similarly to the 'trusted user' group. Only users in the 'debug user' group can user debug mode. If a user outside of this group tries to use any form of debug mode they will be redirected to a version of the page without debug mode enabled.
Story/9774

[ADD] udes_security: Added 'debug user' group

---

addons/udes_stock/models/stock_picking_batch.py

Priority and picking_type_ids are computed from the pickings inside
the batch. A change was made in a previous commit to preserve their
value in case all the pickings of the batch were removed from it.
When the id of the batch is newID it shouldn't try to preserve it.

[FIX] udes_stock: Handle newID at stock.picking.batch computed fields

---

addons/udes_stock/models/stock_move_line.py

Fix issue when batch picking for where multiple move lines share same lot number
Code removed speeds search for later iterations when no lot numbers are duplicated by removing lot numbers from list after use; however, multiple duplicate lot numbers are expected in a batch picking.

[FIX] Fix issue when picking where multiple move lines share same lot number

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py

User-story/9977
Task/10018
MoveLines has its own state attribute, it doesn't need to get it via
picking_id.

[IMP] udes_stock: remove dotted name in domain

---

addons/udes_stock/models/stock_quant_package.py

When not stored can cause issues on action_done() when removing a
package from its parent package since it is recomputing the packages
depths which ends up calling _check_not_multi_location().
Having it stored prevents the check to happen when recomputing the
packages depths.

[FIX] udes_stock: Store u_top_parent

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/data/ir_cron.xml
addons/udes_sale_stock/models/sale_order.py

* Add confirm_orders() method to sale order so that they are confirmed in batches and committing after each batch to give visibility.
* Add cron job to execute confirm orders but disabled.

User-story: 10074 - Confirm orders in batches and committing

---

addons/udes_common/models/models.py

If the method already exists on the base model then log the message
instead of raising an import error.
User-story: 9138

[FIX] Log message if method already exists on base module.

---

addons/udes_security/__manifest__.py
addons/udes_security/data/ir_config_parameter_data.xml
addons/udes_security/models/res_users.py

Added system parameter "inactive_session_time_out_enabled" to allow the timeout check in auth_session_timeout to be disabled.
Story/9964

[ADD] udes_security: Add inactive_session_time_out_enabled system parameter

---

addons/udes_security/__manifest__.py
addons/udes_security/controllers/__init__.py
addons/udes_security/controllers/main.py
addons/udes_security/data/blocked_file_type_data.xml
addons/udes_security/models/__init__.py
addons/udes_security/models/blocked_file_type.py
addons/udes_security/models/ir_attachment.py
addons/udes_security/security/ir.model.access.csv
addons/udes_security/static/src/js/binary_fields.js
addons/udes_security/tests/__init__.py
addons/udes_security/tests/files/json_file.json
addons/udes_security/tests/files/rtf_file.rtf
addons/udes_security/tests/files/spreadsheet_file.csv
addons/udes_security/tests/files/text_file.txt
addons/udes_security/tests/test_blocked_file_type.py
addons/udes_security/tests/test_file_controllers.py
addons/udes_security/views/blocked_file_type_views.xml
addons/udes_security/views/webclient_templates.xml

Prevent users from uploading/download executable files via a blocked file type list which is configurable by admin.
Added Blocked File Type entity which allows admin user to add file types which non-admin users will not be able to download.
Attachments matching blocked file types now hidden. Upload and Download controllers overridden to explicitly prevent blocked file types from being uploaded/downloaded.
Added override to BinaryFile/BinaryImage widgets so that the file type is checked and upload is prevented if file type is blocked.
Common executable file types added as Blocked File Types.

Story/9770 - Blocked file type filtering

---

addons/udes_sale_stock/models/sale_order_line.py

If the lines are flagged as is_cancelled when in state draft, the confirmation of
the order will create moves for them anyway. Therefore, they have to be filtered
out so moves are not created.

[FIX] udes_sale_stock: Ignore cancelled lines at _action_launch_procurement_rule()

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_stock_inventory.py
addons/udes_stock/views/stock_inventory.xml
addons/udes_stock/views/stock_warehouse.xml

A new config option may be specified on the warehouse to disallow
inventory adjustments on reserved quants. A warning will appear
if attempted and the user will be blocked from validating with
this setting or if not performed by a debug user.

[ADD] udes_stock: Restrict inventory adjustment on reserved stock

---

addons/udes_sale_stock/__manifest__.py
addons/udes_sale_stock/models/__init__.py
addons/udes_sale_stock/models/edi_sale_request_document.py
addons/udes_sale_stock/models/edi_sale_request_record.py
addons/udes_sale_stock/models/partner_pii.py
addons/udes_sale_stock/models/res_groups.py
addons/udes_sale_stock/models/res_users.py
addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/sale_order_line.py
addons/udes_sale_stock/models/stock_move.py
addons/udes_sale_stock/models/stock_move_line.py
addons/udes_sale_stock/models/stock_warehouse.py
addons/udes_sale_stock/tests/common.py
addons/udes_sale_stock/tests/test_cancel_unfulfillable.py
addons/udes_sale_stock/tests/test_get_current_demand.py
addons/udes_sale_stock/views/edi_sale_request_views.xml
addons/udes_sale_stock/views/sale_order_views.xml

Customer Reference and Requested Date fields on Sales Orders now required.
Customer Reference and Requested Date fields also moved to the top section of Sales Orders view to be more prominent.
"(copy)" appended to Customer Reference when an Order is copied, as this field now needs to be set on a copied Order.
Updated create_sale function in BaseSaleUDES unit test class to now put in default Customer Reference and Requested Date.
Black formatting run on Python files.

Story/10507 - UDES Sale Stock - Make Requested Date and Customer Reference fields required for Sales Orders

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_move_line.py
addons/udes_stock/tests/test_update_picking.py

[FIX] udes_stock: Fix typo in update_picking drop location tests
All the drop location tests use the Pick picking type, but the setup method
was setting the target storage format for Goods In instead.
-------------------------------------------------------------------------------
[IMP] udes_stock: Add drop off support to update_picking
When a destination location is passed to update_picking and no source package
name or products are specified, update the destination location of all done
move lines. This models a drop off operation.
The set of move lines to be updated may be narrowed down by passing a result
package name / pallet name.
User-story: 10335 …

[IMP] udes_stock: Drop off support in update_picking and allow drop off at damaged stock locations

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_splitting.py

To remove all empty pickings via unlink_empty we need to call it
on both the current pickings and its next pickings. If we don't,
then after the first refactor the empty pickings don't get removed
because they are no longer linked.
User-story: 10475

[IMP] stock_picking: Call unlink_empty on next pickings

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py

User-story/10682
Task/10863
The suggested locations feature should consider partially available move
lines when determining available locations.

[FIX] udes_open: Do not suggest locations with partially available lines

---

addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_stock_inventory.py

Add test to check impact of inventory adjustment to move lines
This is to test a fix on Odoo core stock.move.line._free_reservation().

User-story: 10430

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

Added Restrict Multi Lot Transfers flag to Picking Types. When validating a picking a check is carried out to see if the Picking Type restricts multi lot transfers. If it does and the move lines contain more than one unique lot an exception is raised.
Added Unit Test for multi lot picking restriction in TestPickingType.

Story/10703 - Restrict Multi Lot Transfers flag on Picking Types

---

addons/udes_security/models/__init__.py
addons/udes_security/models/res_partner.py

Ensured that the strength and history of the password are checked prior to resetting the signup token. This means that any discrepancies are found earlier and will allow the user to subsequently provide a valid password successfully.
Story/1380

[FIX] udes_security: Credentials checked before resetting signup token

---

addons/udes_stock/controllers/stock_picking_batch.py

Added lot_name as an optional parameter to the unpickable item function to allow the unpickable item functionality to be used when a product is tracked by lot.
Story/11017

[FIX] udes_stock: Added lot_name to unpickable_item

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_target_storage_types.py

Raise an error if a move line would end up with its result parent package
in multiple locations. An error would usually be raised at picking validation
time, but this is too late - by this time other move lines may also have an
invalid result parent package set and labels may have been printed.
User-story: 10539

[IMP] udes_stock: Raise error when result parent package has wrong location

---

addons/udes_sale_stock/models/sale_order.py

… cancel
Function which cancels orders without availability did not
discriminate, acting upon all orders, changed this to except
a further domain for the search to improve specificity.

[IMP] udes_sale_stock: Add auxiliary domain to find orders to cancel

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/stock_move.py

- Added ability to not cancel sale lines when cancelling move
lines using a context variable
User-story: 10626

[ADD] udes_sale_stock: Can keep sale lines when cancelling moves

---

addons/udes_stock/models/stock_quant.py
addons/udes_stock/tests/test_stock_quant.py

Changed the default FIFO order by from `on_date ASC NULLS FIRST, id` to
`on_date ASC NULLS FIRST, package_id NULLS FIRST`.
User-story: 11534
Task: 11629

[IMP] udes_stock: Update FIFO removal strategy

---

addons/udes_stock/views/stock_picking.xml

On the stock picking screen, once a move has been complete (or has
partial qty assigned) it should be clearly shown with colour coding
to highlight descrepancies. (story/11411)

[IMP] udes_stock: Improve descrepancy highlighting of stock moves

---

Dockerfile
addons/udes_delivery_control/__init__.py
addons/udes_delivery_control/data/picking_types.xml
addons/udes_delivery_control/models/stock_picking.py
addons/udes_delivery_control/tests/__init__.py
addons/udes_delivery_control/tests/common.py
addons/udes_delivery_control/tests/test_delivery_control_workflow.py
addons/udes_delivery_control/tests/test_related_pickings.py
addons/udes_stock/tests/test_picking.py

Allows for Delivery Control pickings to be completed and cancelled without the need for any moves.
Goods In picking generated when Delivery Control picking completed (if it doesn't have one linked already). Cancelling a Delivery Control picking will also cancel the linked Goods In, and Goods In cannot be completed if the linked Delivery Control picking is in a pending state.
Computed first/previous/next picking fields overridden to take into account Delivery Control pickings.
Unit tests added and udes_delivery_control module added to udes_open Dockerfile.
~~Note: There are some TODOs in the code relating to required fields which are part of story 11446. These will be addressed when that story has been merged in.~~

Story/11461 - Delivery Control picking type functionality

---

addons/udes_stock/views/stock_picking.xml

Partners/ Suppliers can now be created quickly via the stock.picking form.
Story/11792

[IMP] udes_stock: Enabled ability to create partners on pickings

---

addons/udes_stock/README.md
addons/udes_stock/__manifest__.py
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/views/stock_warehouse.xml
addons/udes_stock/wizard/__init__.py
addons/udes_stock/wizard/stock_backorder_confirmation.py
addons/udes_stock/wizard/stock_backorder_confirmation.xml

Add `u_disable_no_backorder_button_picking_type_ids` to stock.warehouse, and
`u_disable_no_backorder_button` to stock.backorder.confirmation. This allows
easier configuration of the picking types that must always create a backorder
when validating in the UI when not everything is available/done.
User-story: 11495

[ADD] udes_stock: Add field to disable the `No backorder` button

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_picking_type.py
addons/udes_stock/views/stock_picking.xml
addons/udes_stock/views/stock_picking_type.xml
addons/udes_stock/views/stock_quant_views.xml

- New button on the inventory dashboard shows the number of packages at a location for a picking type
- Existing "Transfers" button can be shown/ hidden based upon config for the picking type. This should be shown for all picking types

Story 11973

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_picking_batch.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_picking_batch.py
addons/udes_stock/views/stock_picking_type.xml

- Added config to allow user to skip based on move_lines
in addition to products
- Added config to allow the user to return to skipped items
- Added unit tests for skipping
User-story: 11993
Changed get_next_task to allow it to return to skipped tasks. In the process of doing this I refactored it to improve the flow and allow some of the functionality to be used for future purposes (returning list of all remaining tasks)

[ADD] udes_stock: Improve skip functionality

---

addons/udes_priorities/models/stock_picking.py
addons/udes_priorities/models/stock_picking_batch.py

Bug 1: active_id on dashboard is the picking_type not the pick
Bug 2: orm was cachinng values for priorites accessed via another pick
Bug 3: adding second move to picking threw an error

[FIX] udes_priorities: Fixes three bugs

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_picking.py
addons/udes_stock/views/stock_picking.xml

Unlocked pickings (e.g. Goods In Pickings generated from completed Delivery Control pickings) are now locked once marked as todo or as an extra safety check, when the picking is completed.
Fixed issue with Stock Picking form override that was only hiding the Unlock button and not Lock.
Added Unit Test to ensure unlocked pickings are locked once confirmed or completed.

Story/11767 - Lock pickings once confirmed/completed

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/tests/test_push_from_drop.py

Propagate origin and partner_id from picking
In case the moves do not propagate it, propagate it from the picking
since some times they are empty at the moves but not at the picking.

User-story: 12162 

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/tests/test_stock_inventory.py

Refactored _get_inventory_lines_values from core Odoo, with logic for filtering and retrieving line values split out into separate functions which can be easily overridden in other modules if needed.
Rather than using SQL to retreive the values to use for Inventory Lines, a search with the appropriate filter is now carried out on Quants, with a key used to identify unique quants in a dictionary of values. If the key is already found, the quantity is updated.
Story/11983

[IMP] udes_stock: _get_inventory_lines_values refactored

---

addons/udes_priorities/models/priority.py

Checks for install_mode flag and bypasses the check for outstanding pickings if True.

[FIX] udes_priorities: Ensure pickings are not checked if installing

---

addons/udes_stock/models/stock_picking.py

Rely on the code inside action_confirm() to do so, since it uses
a list of fields to take into account instead of just product.
User-story: 12377

[IMP] udes_stock: Remove smart merging at _create_moves()

---

addons/udes_stock/models/stock_picking.py

When raising a stock investigation we should only consider quants
that still exist, as merging of quants may happen due to removal
of additional information when unreserving.

[FIX] udes_stock: Fix for merged quants in raise stock inv

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/models/stock_quant_package.py
addons/udes_stock/tests/test_stock_inventory.py
addons/udes_stock/views/stock_inventory.xml

Parent Package field added to Stock Inventory Line. This means the parent package will be retained when a Quant is adjusted. The parent package can also be updated in the Inventory Adjustment screen.

Story/12266 - Parent Package added to Inventory Adjustment screen

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/sale_order_line.py

If "cancelled_stock_shortage" is set in context, the Cancelled Due to Stock Shortage flag will now be written to the Order Line in action_cancel. This saves a write on the lines after they have been cancelled in "cancel_orders_without_availability"
Story/11984

[IMP] udes_sale_stock: Cancelled Due to Stock Shortage now set on action_cancel on Sale Order Line

---

addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_quant_views.xml

Added create date field to Stock Quant list view to show the date the quant was last moved. Field is hidden by default but is shown when viewing package counts via the Inventory Dashboard.
Story/12608

[IMP] udes_stock: Create date added to Stock Quant list view, hidden by default

---

addons/udes_security/__manifest__.py
addons/udes_security/views/base_language_install_view.xml
addons/udes_security/views/base_menu.xml

In order to accommodate the scenario where users without system administration/access rights permissions still need access to certain menus in settings, the groups set directly against the top Settings menu item have been removed.
The settings menu will now show if the user has access to any sub menu items. Because of this, appropriate security groups have been added to User/Companies and Translation menus.
Story/12629

[IMP] udes_security: Removed groups set directly on main Settings menu item

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

Added `u_show_scanned_pallets` option. Original implementation is at goods in when changing a pallet.
Story/12709

[ADD] udes_stock: Added u_show_scanned_pallets to picking types

---

addons/udes_delivery_control/models/stock_picking.py
addons/udes_delivery_control/models/stock_picking_backload.py
addons/udes_delivery_control/views/stock_picking.xml

[IMP] udes_delivery_control: Only set default supplier on backload record if the picking supplier does not already have a backload record

---

addons/udes_stock/views/stock_picking.xml

The original invisible condition can be found here: https://github.com/unipartdigital/odoo/blob/udes-11.0/addons/stock/views/stock_picking_views.xml#L217

[FIX] udes_stock: Show Unreserve button for partially reserved pickings

---

addons/udes_stock/models/stock_location.py
addons/udes_stock/models/stock_picking.py

Added the ability to provide details of the moves to the picking's mail.thread for PI count moves e.g. when additional packages are present in the location.
Story/12762

[ADD] udes-open: Added move details to PI count moves

---

addons/udes_warehouse_classification/__init__.py
addons/udes_warehouse_classification/__manifest__.py
addons/udes_warehouse_classification/models/product_warehouse_classification.py
addons/udes_warehouse_classification/tests/__init__.py
addons/udes_warehouse_classification/tests/test_add_product_classification.py
addons/udes_warehouse_classification/views/warehouse_product_classification.xml
addons/udes_warehouse_classification/wizard/__init__.py
addons/udes_warehouse_classification/wizard/add_product_classification.py
addons/udes_warehouse_classification/wizard/add_product_classification_view.xml

story/12429
This change enables uploading a file of product template default codes
and having the corresponding product templates tagged with the selected
warehouse classification codes.

[IMP] udes_warehouse_classification: Product classification upload

---

addons/udes_priorities/models/priority_groups.py

So that changes to a priorities picking type are also propogated to the group

[FIX] udes_priorities: Extend depends on groups pick type computation

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/views/stock_picking_type.xml

- When partial reservation of a picking is enabled there is
now the option to only allow this by entire move lines rather
than partial move lines
User-story: 12840

[ADD] udes_stock: Add option to only reserve full lines

---

addons/udes_stock/models/product_product.py

Instead of showing all of the serials used in the search we want
to show only the result of all serials in use already
User-story: 11395

[FIX] udes_stock: Change error to show only duplicate serials

---

addons/udes_sale_stock/models/sale_order.py
addons/udes_sale_stock/models/sale_order_line.py
addons/udes_sale_stock/models/stock_warehouse.py
addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/test_manual_sale_order_line_cancellation.py
addons/udes_sale_stock/views/sale_order_views.xml
addons/udes_sale_stock/views/stock_warehouse.xml

Replaces https://github.com/unipartdigital/udes-open/pull/460
The previous PR disallowed cancellation if the outbound process was in progress. 
This PR allows it as long as no picking in the outbound process is in progress:
Sale order lines may be manually cancelled if there are no pickings in
progress. Note that this is not the same as the outbound process being
in progress: sale order lines may be cancelled midway through the outbound
process as long as no one is working on a picking related to it.
Sale order lines may not be cancelled once their products have progressed
to a certain stage of the outbound process, controlled by the
u_disallow_manual_sale_order_line_cancellation_at_picking_type_ids setting
on the warehouse. Eg. cancellation can be disallowed once products are about
to be …

[ADD] udes_sale_stock: Implement manual cancellation of sale order lines

---

addons/udes_stock/models/stock_picking.py

with scanned package instead of expected package
Story: 12656

[FIX] udes_open: Changing the error message

---

addons/udes_stock/models/stock_picking.py

To fix slowness of the sorting when fetching many empty locations. We limit the returned empty locations to the 50 before we sort them by name.

[FIX] udes-open Adds a limit to empty locations returned.

---

addons/edi_sale_notifier/tests/test_sale_notifier.py

- Tests fail as some fields are made required by addons not in the
manifest of edi_sale_notifier
- These fields will be now populated in these tests
User-story: 14441
CI bump?

[FIX] edi_sale_notifier: Fix failing tests

---

addons/udes_stock/controllers/stock_move_line.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py

Allowing sorting and limit optionally in suggested_locations, sorting
is for all policies, limit only for those that accept it (story/14394)

[FIX] udes_stock: Add optional limit and sort to suggested locations

---

addons/udes_stock/models/stock_picking_batch.py

Sometimes, due to refactoring, `to_investigate` can exist in cache
but not in the database. Check it exists before operating on it
User-story: 14596

[FIX] udes_stock: MissingError when raising stock investigation

---

addons/udes_stock/models/stock_location.py
addons/udes_stock/tests/test_location_state.py

story/179
Set `Location.u_state` to "archived" when `Location.active` is set to
`False`.

[IMP] udes_stock: Add "archived" location state.

---

addons/udes_priorities/__manifest__.py
addons/udes_priorities/models/priority.py
addons/udes_priorities/tests/common.py
addons/udes_priorities/tests/test_priority.py
addons/udes_priorities/views/priorities.xml

When adding a new stock transfer type to a priority if there was a
picking that is not yet completed then UDES would complain of this
and not let any user modify the list of assigned stock transfer types.
This change adds the ability for sysadmin, debug and trusted users
to modify the list of stock transfer types for priorities and also
see the outstanding pickings for the priority in question.
User-story: 20

[FIX] udes-open: restrict ability to add picking types to priorities

---

addons/udes_stock/models/stock_move.py
addons/udes_stock/tests/test_refactoring_splitting.py

When refactoring, only keep done dates for complete pickings
User-story: 19

[FIX] udes_stock: Don't propagate done dates to incomplete pickings

---

addons/udes_stock/controllers/stock_location.py

Provide the information that the call is coming from a mobile
user and not from the desktop interface.
User-story: 486

[IMP] udes_stock: add a mobile value to differentiate caller

---

addons/udes_stock/README.md
addons/udes_stock/controllers/stock_location.py

The user only finds out about different location in package when tries
to valid the picking the after all pickings been done. These can be time consuming
and more work for team lead to rectify the locations on a picking in case of
locations are different.

[FIX] udes_stock: Check the package locations when selecting package

---

addons/udes_stock/utils.py

Add a function to format dictionary into a list of key and value for
displaying dictionary values into display components.
User-story: 9

[IMP] udes_stock: add util to format dictionaries for display components

---

addons/udes_stock/models/__init__.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/models/stock_location_route.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/models/stock_warehouse_orderpoint.py

Disable name translation for picking types and routes,
this avoids complications when duplicating, where the
new duplicated name was not being saved and was being
treated as a translation.
User-story: 621

[FIX] udes_stock: Disable name translation

---

addons/udes_common/models/__init__.py
addons/udes_common/models/res_users.py

Returns true if user is superuser or admin (admin user created by default by Odoo).
Story/567

[ADD] udes_common: Added _is_superuser_or_admin method to ResUsers

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_move_line.py
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_quant.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_stock_location.py
addons/udes_stock/tests/test_stock_move.py
addons/udes_stock/tests/test_stock_move_line.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/tests/test_stock_quant.py
addons/udes_stock/tests/test_stock_quant_package.py

Use product_uom_qty throughout as product_qty is a computed
field. This is a backend change, and further changes need
to be done to handle different UoMs in both the frontend
and in Odoo.
User-story: 462

[IMP] udes_open: Handle UoM in udes_stock

---

addons/udes_stock/report/location_templates.xml

Fix to allow multiple location barcodes to be printed without overlapping. Page breaks were not working prior to this fix.
Story/X1016

[FIX] udes_stock: Allow multiple location barcodes

---

addons/udes_ldap/README.md
addons/udes_ldap/__init__.py
addons/udes_ldap/__manifest__.py
addons/udes_ldap/models/__init__.py
addons/udes_ldap/models/res_company_ldap.py
addons/udes_ldap/security/ir.model.access.csv
addons/udes_ldap/views/res_company_ldap_views.xml

story/955
Code and configuration for the UDES LDAP module.
UDES LDAP overrides the Odoo auth_ldap and the OCA auth_ldaps addons
to enable authentication over LDAP using the user's LDAP credentials to
bind to the LDAP server rather than a service account.

[ADD] udes_ldap: UDES LDAP addon.

---

addons/udes_stock/views/stock_picking.xml

Added a readonly attribute for destination_location on when the state is not in draft to prevent circumventing the he checks already  in place by changing the destination-location on a check peacemeal.
Story/965
Signed-off-by: Nick Costa <nicholas.costa@unipart.io>

[FIX] udes_stock: Added readonly attr when not in draft

---

addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_picking.py

The tests here use an helper method to create a picking instead
of using for example create_picking() in stock.picking model.
Bebcause of this there can be differences in the tests in terms
of how a picking is cretated which can mean a different behaviour
compared to UDES is tested.
This change aligns better how a picking is created compared to UDES.
User-story: 840

[IMP] udes_stock: origin in stock.move not set correctly

---

addons/udes_delivery_control/views/stock_picking.xml
addons/udes_stock/__manifest__.py
addons/udes_stock/data/stock_picking.xml
addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_batch.py
addons/udes_stock/views/stock_picking.xml

Added "_set_original_picking_on_historical_pickings" which identifies
any pickings in the system that don't have "u_original_picking_id" set
and sets the value.
Method call in XML which is run when udes_stock is installed or updated.
Story/907

[ADD] udes_stock: Add method to set orig picking on pickings

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/views/stock_picking.xml

[IMP] udes_stock: Add batch user_id to the picking list view.
- Add the user responsible for the batch, to which the picking belongs, to the picking list view.
Story/1384

Story #1384 See who is assigned to a batch from the picking screens

---

addons/udes_stock/models/stock_picking.py

User-story: 898
As per requested by Miquel, improve the way the priorities domain
check is performed as it would result in failed search when the
parameter is an empty list.

[IMP] udes_stock: Improve picking priority domain check

---

addons/udes_stock/README.md
addons/udes_stock/models/mixin_stock_model.py
addons/udes_stock/models/stock_quant_package.py

User-story: 1169
The find_move_lines() function in stock.quant.package is not checking
for move lines that use the package as a destination package. This
change ensures this check is done.
The get_or_create() fucntion in the mixin stock model does not allow
for returning an empty result without raising an issue. Adding here
the support for such use case.

[IMP] udes_stock: Adding support for finding packages

---

addons/udes_simple_location_blocking/README.md
addons/udes_simple_location_blocking/__init__.py
addons/udes_simple_location_blocking/__manifest__.py
addons/udes_simple_location_blocking/models/__init__.py
addons/udes_simple_location_blocking/models/stock_inventory.py
addons/udes_simple_location_blocking/models/stock_location.py
addons/udes_simple_location_blocking/models/stock_move.py
addons/udes_simple_location_blocking/models/stock_move_line.py
addons/udes_simple_location_blocking/models/stock_picking.py
addons/udes_simple_location_blocking/models/stock_quant.py
addons/udes_simple_location_blocking/tests/__init__.py
addons/udes_simple_location_blocking/tests/common.py
addons/udes_simple_location_blocking/tests/test_inventory.py
addons/udes_simple_location_blocking/tests/test_location.py
addons/udes_simple_location_blocking/tests/test_move.py
addons/udes_simple_location_blocking/tests/test_move_line.py
addons/udes_simple_location_blocking/tests/test_picking.py
addons/udes_simple_location_blocking/tests/test_quant.py
addons/udes_simple_location_blocking/views/stock_location.xml
addons/udes_stock/models/stock_picking.py
addons/udes_suggest_location/__manifest__.py
addons/udes_suggest_location/registry/suggest_by_empty_location.py
addons/udes_suggest_location/registry/suggest_exactly_match_move_line.py
addons/udes_suggest_location/tests/test_stock_move_line.py
addons/udes_suggest_location/tests/test_suggest_by_empty_location.py

[IMP] udes_simple_location_blocking: Add new module for blocking locations
User-story: 1277
Add a new module from UDES11 to block locations from being used by pickings,
stock moves, stock move lines and stock inventory adjustments.
Also avoid stock quantities that are in blocked location from being used.
Additionally, this module is now a dependency of udes_stock and udes_suggest_location.

[IMP] udes_simple_location_blocking: Add new module for blocking locations

---

addons/udes_stock_picking_batch/models/stock_picking_batch.py

Update the state field on the stock.picking.batch model to use selection_add instead of redefining all the states.

[FIX] udes_stock_picking_batch: Update to selection_add

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_backorder.py

[FIX] udes_stock: Stops backorder being created for cancelled movelines

---

addons/udes_stock_picking_batch/models/stock_picking.py

This fixes the test for the backordering logic where the batch state
is not being updated after the picking is done.
User-story: x1800

[IMP] udes_stock_picking_batch: Recompute state after action done

---

addons/udes_stock/data/picking_types.xml
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/models/stock_warehouse.py
addons/udes_stock/tests/__init__.py
addons/udes_stock/tests/test_stock_picking_type.py
addons/udes_stock/tests/test_stock_warehouse.py
addons/udes_stock/views/stock_picking_type.xml

[IMP] udes_stock: Ensure that the prefixes of picking types are consistent with the UDES style and not Odoo's style.
The sequence_code field is not needed in UDES as it is used strictly in the Odoo style sequence (which we do not want). When updating picking_types, if there was sequence_code field in the values to update, Odoo was hardcoded to update the sequences on the picking types to the Odoo prefix style. This resulted in changes to prefixes when changing data on the picking type, such as updating the picking_type with data that set a sequence_code.
Additionally when the warehouse is created or updated with a new name or code, Odoo would update the picking type sequence prefixes.  _get_sequence_values() was were these new picking_type sequences prefixes were generated. This method …

#1805 Stock - Picking Types handled inconsistently

---

addons/udes_stock/views/stock_picking.xml
addons/udes_stock_picking_batch/views/stock_picking_batch.xml

Refactor buttons that are not necessary and rename cancel pickings
button to make it easy to distinguish from discard changes.
User-story: x1804

[IMP] udes_stock,udes_stock_picking_batch: Refactor Buttons

---

addons/udes_stock/models/stock_inventory.py

This was a side-issue discovered during sign off, prevents zeroed lines with pallet change information from actually changing pallet information.
If a quantity is specified, then the parent package change still needs to occur, but in instances where no quantity is specified, then either moves will be generated to write off the quantity, or (if no theoretical quantity) nothing will happen with any quants
User-story: 1402

[FIX] udes_stock: Do not change parent package if no quantity specified

---

addons/udes_common/tools/__init__.py
addons/udes_common/tools/relational_field_operators.py

Odoo operators for one2many and many2many fields added into enum class
with descriptive names.
Useful in cases where operators are evaluated to make the code
more readable.
Story/1910

[ADD] udes_common: Relational field operators enum class added

---

addons/udes_stock_refactoring/models/stock_move.py
addons/udes_stock_refactoring/models/stock_move_line.py

When computing the grouping key for Move/Move Line,
if `compute_key` was not in context then the compute method was
previously returning without assigning a value.
In Odoo 14 this is not allowed and will lead to an exception.
To avoid this Move/Move Line will have None set by default.

[FIX] udes_stock_refactoring: Always set value for grouping key

---

addons/udes_sale/views/sale.xml
addons/udes_sale_stock/__init__.py
addons/udes_sale_stock/models/stock_move.py
addons/udes_sale_stock/tests/__init__.py
addons/udes_sale_stock/tests/test_sale_order.py

A default filter was removed from the search bar on the Quotations page. 
All pickings associated with a Sale Order are now linked to the sale order, and all moves are now linked to a sale order line. 
The fix involved ensuring that sale_line_id was propagated with other move information down the procurement rule chain (as they are created recursively) i.e. move information for one picking type is given to a picking type down the chain to create a move and on and on. This way all moves in the chain were attached to the sale order.

Story #2021 Sale - Orders Improvements and Fixes

---

addons/udes_stock/data/res_users.xml

Admin user is not restricted by ACLs, however there are some instances
where specifc user groups are checked against a user, so the
inbound/outbound/stock groups have been added to the user to ensure
it will not have operations blocked because it lacks any of these
groups.
Issue/2297

[ADD] udes_stock: Security groups added to Admin user by default

---

addons/udes_stock/views/stock_picking.xml

UDES has a wizard for reserving/unreserving multiple pickings, so the
built in Odoo actions have been hidden.
Server action is no longer binded to the picking model, and the button
in the tree view has been made invisible.
Story/2428

[REM] udes_stock: Remove Odoo unreserve picking actions

---

addons/udes_get_info/__manifest__.py
addons/udes_get_info/models/models.py
addons/udes_get_info/tests/test_stock_quant.py

Returning false for related fields when they don't have value, in
this way we always will have the expected fields on get_info.

Fix failing udes_get_info test

---

addons/udes_stock_picking_batch/models/stock_picking_batch.py
addons/udes_stock_picking_batch/views/stock_picking_batch.xml

Removing all pickings sets batch state as done, which makes picking_ids readonly, leading to the changes not being saved.

Story/2423 - Fix bug for removing all pickings from a batch.

---

addons/udes_stock/models/stock_move_line.py
addons/udes_stock/tests/test_stock_move_line.py

[FIX] udes_stock: Missing variable at find_move_lines lambda
* Added missing ml in the lambda function.
* Also have make product_id mandatory, since it does not make sense
to find move lines for a given quantity without specifying product.

User-story: 2500

---

addons/udes_report/tests/test_stock_export.py

The test was failing as it sets tangerine and strawberry tracking to
none, however the ugli product was recently added, which is serial
tracked.
To avoid needing to update this test each time, tracked products
are now searched for and made non-tracked.

[FIX] udes_report: Fix failing test - test_stock_file_tracking

---

addons/udes_stock_inventory/views/stock_inventory_views.xml

Was removed as part of story 2183, but accidentally added back as the
override was moved from udes_stock to udes_stock_inventory.
Story/2466

[REM] udes_stock_inventory: Remove Inventory help text override

---

addons/udes_stock/data/picking_types.xml
addons/udes_stock/data/routes.xml

Set Replen picking type and routes to inactive by default. To be enabled by config in relevant modules.

[IMP] udes_stock: Set Replen to inactive by default

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py

Stops done/cancelled pickings having their priorities
set to "Normal"
User-story: 2433

[FIX] udes_open: Stop resetting priorities on pickings

---

addons/udes_stock/tests/test_stock_picking.py

Skip test_priority_one_remains_on_done_picking as it relies on an Odoo
change, and CI will fail until the odoo-tester image can be rebuilt.
To be reverted once the odoo-tester image is updated.

[FIX] udes_stock: Temporarily skip unit test for picking priority

---

addons/udes_stock_picking_batch/models/stock_picking_batch.py

Mobile users cannot an exception on a pick when the picking gets
assigned to a new batch since they do not have the right permissions
to perform write operations for batches. This commit addresses
this issue as this operation should be performed regardless of
the user permissions.
User-story: x2427

[IMP] udes_stock_picking_batch: Solve issue with batch user permissions

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/views/stock_picking_type.xml

[IMP] udes_stock: Add fields which allow grouping of pickings across backorders.
Story/2319
Signed-off-by: Jack Birch <jack.birch@unipart.io>

Story #2319 Order Status Reporting

---

addons/udes_stock/report/deliveryslip_templates.xml

Add source document to each stock move line. Rename table headings and
add picking reference number.
Story: x2422

[IMP] udes_stock: Implement delivery slip for multiple source documents

---

addons/udes_security/controllers/main.py

Handle case where action_id is string, e.g. if an action is specified
in a view for another XML record.

[FIX] udes_security: Harden _get_menu_info_from_action_id

---

addons/udes_security/__manifest__.py
addons/udes_security/controllers/redirect.py
addons/udes_security/data/res_groups.xml
addons/udes_security/data/res_users.xml
addons/udes_security/data/setup_default_domains.xml
addons/udes_security/models/__init__.py
addons/udes_security/models/domain_allowlist.py
addons/udes_security/security/ir.model.access.csv
addons/udes_security/tests/__init__.py
addons/udes_security/tests/test_no_redirect.py
addons/udes_security/views/domain_allowlist_view.xml

Porting of the code that implements the allowlist domain filter model
for blocking redirections from UDES13. This code implements a list to
filter domains and block redirection requests if the domain is not in
the list filter. The list has been renamed from whitelist to allowlist.
Story: x2536

[IMP] udes_security: Port of redirection domain filter list

---

addons/udes_stock/README.md
addons/udes_stock/models/stock_move.py
addons/udes_stock/models/stock_picking_type.py
addons/udes_stock/tests/test_stock_move.py
addons/udes_stock/views/stock_picking_type.xml

This includes a new option `u_propagate_cancel` on `stock.picking.type`
to turn the functionality on.
User-story: 2411

[ADD] udes_stock: Move (and partial) cancellation propagation

---

addons/udes_stock/__manifest__.py
addons/udes_stock/views/stock_orderpoint_views.xml

Set only 1 view under Operations menu for orderpoint rules also called
Replenishments. We only want to use automatic rules so the view will
display automatic rules by default. For this purpose the Reordering Rules
menu and view have been moved under the Operations menu and renamed as
Replenishments. This is not to be confused with the Replenishments menu
offered by Odoo14 which has been disabled.
Story: x2613

[IMP] udes_stock: Refactor views for orderpoint rules under 1 view

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/views/stock_inventory.xml

Change stock.inventory exhausted field
Avoid potential issues when large number of products in the system:
* Hide check box from the form view
* When changing filter set to exhausted=False

User-story: 2818

---

addons/udes_stock/models/stock_inventory.py
addons/udes_stock/views/stock_inventory.xml

Change stock.inventory exhausted field
Avoid potential issues when large number of products in the system:
* Hide check box from the form view
* When changing filter set to exhausted=False

 User-story: 2818

---

addons/udes_security/controllers/redirect.py

Avoids deprecation warning:
"DeprecationWarning: The import 'werkzeug.url_unquote' is deprecated
and will be removed in Werkzeug 1.0. Use 'from werkzeug.urls
import url_unquote' instead."
Issue/2810

[FIX] udes_security: Fix deprecation warning for werkzeug url_unquote

---

addons/udes_simple_location_blocking/tests/test_inventory.py
addons/udes_simple_location_blocking/tests/test_move.py
addons/udes_simple_location_blocking/tests/test_move_line.py
addons/udes_simple_location_blocking/tests/test_picking.py
addons/udes_stock/models/mixin_stock_model.py
addons/udes_stock/models/stock_location.py
addons/udes_stock/models/stock_quant_package.py
addons/udes_stock/tests/common.py
addons/udes_stock/tests/test_limit_orderpoints.py
addons/udes_stock/tests/test_mixin_stock_model.py
addons/udes_stock/tests/test_product.py
addons/udes_stock/tests/test_res_users.py
addons/udes_stock/tests/test_stock_location.py
addons/udes_stock/tests/test_stock_move.py
addons/udes_stock/tests/test_stock_picking.py
addons/udes_stock/tests/test_stock_picking_type.py
addons/udes_stock/tests/test_stock_picking_user_assignment.py
addons/udes_stock/tests/test_stock_quant.py
addons/udes_stock/tests/test_stock_quant_package.py
addons/udes_stock/views/stock_location_views.xml
addons/udes_stock_routing/tests/test_push_from_drop.py
addons/udes_suggest_location/tests/test_stock_move.py
addons/udes_suggest_location/tests/test_stock_move_line.py
addons/udes_suggest_location/tests/test_suggest_by_empty_location.py
addons/udes_suggest_location/tests/test_suggest_exactly_match_move_line.py

Internal locations locked down to prevent being able to have child locations.
Updated various tests to work nicely with this new constraint.
Added and updated helper methods.
Added sudo parameter for get_or_create for stock mixin.

Story/757 - Prevent internal locations from having child locations

---

addons/udes_security/views/no_desktop_access_template_views.xml

story/2765
Condition the appearance of the password reset link for no-desktop users who successfully log in on the value of auth_signup.reset_password.

[IMP] udes_security: Condition password reset link

---

addons/udes_stock/views/stock_location_views.xml

Main group on stock location has three groups, change the layout to three columns so there is one column per group.
Story: 2002

[IMP] udes_stock: Adding col=3 for main group

---

addons/udes_stock/models/stock_location.py

story/2432
Track changes to a location's usage type and parent location id to make analysing support issues easier.

[IMP] udes_stock: Track changes to location.

---

addons/udes_security/controllers/main.py

Backported from UDES 14 commit: https://github.com/unipartdigital/udes-open/commit/581cbbeff3563d3af45cbf2242d51bb80476a1df
Story/3337
Signed-off-by: Peter Clark <peter.clark@unipart.com>

[FIX] udes_security: Handle XML IDs in _get_menu_info_from_action_id

---

addons/udes_stock/tests/common.py

Removing super setupclass on BaseUDESPullOutboundRoute
Story: 3344

[ADD] udes_stock: Removing super setupclass as not needed

---

addons/udes_stock/views/stock_location_route_views.xml

The way we archive or unarchive routes is from actions, which triggers the method to archive or unarchive the rules as well. It's not needed to have 2 places where to archive/unarchive routes
Story: 3205

[FIX] udes_stock: Removing toggle_active from route tree views

---

addons/udes_security/static/src/xml/custom_chatter_topbar.xml

"Schedule activity" button removed for all users and all pages.
Story/4774

[IMP] udes_security: Remove "Schedule activity" from all pages

---

addons/udes_security/__manifest__.py

Added missing XML file to manifest.
Story/4774

[FIX] udes_security: Remove "Schedule activity" from all pages

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py

- If a picking has `u_validate_real_time = True` with 3 move lines, when a move line is updated with qty_done and saved via the desktop, Odoo will send 3 commands to the backend. One updating the move line with qty_done, and another two re-writing the other 2 move lines to the picking. This meant that even when the qty_done was written a backorder would be created (which the 2 other move lines would be written to) they would then be written to the original picking due to the extra commands sent to the backend. The fix was to filter out these commands in this specific situation.
- Another weird behaviour that happened with goods in, meant we could have extra move lines attached to a backorder when the picking was validated through the desktop. These extra move lines were in the `assigned` …

Fixing Odd Desktop Backorder Behaviour

---

addons/udes_warehouse_classification/data/user_template.xml

- No outbound flows currently use warehouse classifications, but outbound admins cannot view products without the warehouse classification read permission. Outbound hht will eventually need this permission anyway so it is best to assign it to the outbound hht user.
Set: 173

[FIX] udes_warehouse_classification: Give outbound hht permissions.

---

addons/udes_stock_refactoring/models/stock_move.py

Swap lambda composition to filter cancelled moves first.

[FIX] udes_stock_refactoring: Remove cancel moves

---

addons/udes_stock/models/stock_quant.py

SE-899
Ported from UDES11 the helper functions to find `stock.move.line`s a `stock.quant` is used in.

[IMP] udes_stock: Helper functions to find stock move lines for a quant

---

addons/udes_priorities/models/stock_picking.py
addons/udes_priorities/tests/test_stock_picking.py

SE-822
In cases where we want to order by priority, we should use the priority's sequence attribute. Make this available on the picking to enable ordering where required.

[FIX] udes_priorities: Compute priority sequence on picking.

---

addons/udes_stock/views/stock_picking.xml

SE-1149
Goods-in, (Receive etc. for van stock) may not have Source set on mobile flow. Editing/cancelling such pickings in waiting/ready state was impossible due to missing source document error. Make it mandatory only in the desktop UI, in draft stage.

[IMP] udes_stock: Make Source Document (origin) on pickings only in draft

---

addons/udes_stock/models/stock_picking.py
addons/udes_stock/tests/test_stock_picking.py

Setting bypass_state_check to True for Support Users in order that they can unlink pickings when they are in cancel or draft states, if in progress will automatically cancel which will unreserve and after unlink

[ADD] udes_stock: Setting bypass_state_check to True for Support Users

---

addons/udes_security/models/ir_attachment.py

There was an issue when trying to install website module as in the website_data.xml there was an image of type url without datas.

[ADD] udes_security: Removing exif data when has datas

---

addons/udes_common/models/fields.py
addons/udes_common/tests/__init__.py
addons/udes_common/tests/test_fields.py

- PreciseDatetime.now function returns a datetime.datetime object.
- Functions that invoke PreciseDatetime.now are updated to support the new return object.
- Review use of the from_string method and its aliases.
SE-1471

Change return type of PreciseDatetime.now

---

addons/udes_stock_routing/models/stock_move.py

* Update stock.move.line picking_id at _split_pick_hook
* Flag original picking as empty at _split_pick_hook

SE-1770 udes_stock_routing: Small tweaks

---

addons/udes_stock_cron/models/stock_picking.py

Fix bug when adding more pickings to reserve. The `u_reserve_batches` field does not exist on the stock.picking model.
Story/SE-1844

[FIX] udes_stock_cron: Bug in reserving stock with a batch

---

addons/udes_stock_refactoring/models/stock_picking.py

Only try to reuse existing picking or split into a new one when refactoring by state done.

[FIX] udes_stock_refactoring: Refactoring state done

---

addons/udes_stock_packaging/models/stock_picking.py

If it is already set in the result, no need to create new seq.

[IMP] udes_stock_packaging: Make result_package_name optional

---

addons/udes_security/models/ir_attachment.py

SE-1760
Remove the check for CSV headers; a CSV file without headers is valid per RFC4180.

[FIX] udes_security: Remove CSV header check,

---

addons/udes_stock/models/stock_location.py

SE-2075
Add an index on the stock location model's default order (complete_name, id).

[IMP] udes_stock: Add index on stock location default order

---

addons/udes_stock_routing/models/stock_move.py

Only trigger split pick to moves that require assignment, because if they are assigned it has already been applied.

[FIX] udes_stock_routing: Split pick hook
